export type SystemGuideSeed = {
  slug: string;
  title: string;
  category: string;
  description: string;
  route: string;
  videoUrl?: string;
  content: {
    purpose: string;
    whenToUse: string;
    steps: string[];
    example: string;
    commonErrors: string[];
    tips: string[];
    warnings: string[];
  };
};

export const systemGuideCategories = [
  "Dashboard & Kontrol Merkezi", "CRM & Müşteriler", "Müşteri & Satış", "Ajans Operasyonu", "Satış Hunisi", "Tahsilat & Karlılık",
  "Görev Yönetimi", "Raporlama Merkezi", "Meta Entegrasyonları", "Google Entegrasyonları",
  "HK Intelligence", "AI Studio", "Dosya & Belge Merkezi", "Kullanıcı Yönetimi", "Ayarlar",
  "Web Site Yönetimi", "Müşteri Paneli", "Sorun Giderme", "HK Agent Hub"
];

const definitions: Array<[string, string, string, string]> = [
  ["Dashboard nedir?", "Dashboard & Kontrol Merkezi", "Ajansın günlük KPI, risk ve aksiyonlarını tek ekranda izleyin.", ""],
  ["HK Intelligence Command Center", "Dashboard & Kontrol Merkezi", "Tahsilat, lead, teklif, görev, müşteri ve entegrasyon sinyallerini günlük öncelik sırasına dönüştürün.", "intelligence-command-center"],
  ["Risk Merkezi", "Dashboard & Kontrol Merkezi", "Operasyon risklerini etki ve aciliyet puanına göre inceleyip ilgili kayda ilerleyin.", "risk-merkezi"],
  ["Müşteri yaşam döngüsü", "CRM & Müşteriler", "Lead aşamasından referansa kadar her müşterinin operasyon evresini izleyin.", "intelligence-command-center"],
  ["Müşteri sağlık ve kârlılık analizi", "Tahsilat & Karlılık", "Tahsilat, görev, temas, rapor ve maliyet sinyallerinden müşteri riskini ve tahmini kârlılığı okuyun.", "intelligence-command-center"],
  ["KPI kartlarını okuma", "Dashboard & Kontrol Merkezi", "Gelir, tahsilat, müşteri, kampanya ve görev kartlarını doğru yorumlayın.", ""],
  ["Kritik görevleri yönetme", "Dashboard & Kontrol Merkezi", "Geciken ve kritik görevleri önceliklendirip ilgili kayda ilerleyin.", "gorevler"],
  ["Hızlı işlemler", "Dashboard & Kontrol Merkezi", "Müşteri, kampanya, görev, tahsilat ve rapor formlarını doğrudan açın.", ""],
  ["Müşteri oluşturma", "CRM & Müşteriler", "Yeni firma profilini iletişim ve sektör bilgileriyle kaydedin.", "musteriler"],
  ["Müşteri düzenleme", "CRM & Müşteriler", "Firma, iletişim ve operasyon bilgilerini güvenli biçimde güncelleyin.", "musteriler"],
  ["Müşteri arşivleme ve geri yükleme", "CRM & Müşteriler", "Aktif olmayan müşterileri kalıcı silmeden arşivleyin ve gerektiğinde geri alın.", "musteriler"],
  ["Müşteri görünürlük ayarları", "CRM & Müşteriler", "Müşteri panelinde hangi rapor, ödeme, görev ve dosyanın görüneceğini yönetin.", "musteriler"],
  ["Müşteri paneli kullanıcısı oluşturma", "CRM & Müşteriler", "Firmaya bağlı güvenli müşteri hesabı ve panel erişimi oluşturun.", "kullanici-yonetimi"],
  ["Lead oluşturma ve düzenleme", "Satış Hunisi", "Potansiyel müşteriyi iletişim, sektör, skor ve takip bilgileriyle yönetin.", "satis-hunisi"],
  ["Kanban drag & drop", "Satış Hunisi", "Lead kartlarını onaylı sürükle-bırak akışıyla aşamalar arasında taşıyın.", "satis-hunisi"],
  ["Lead skorlama", "Satış Hunisi", "Sıcak, ılık ve soğuk lead skorlarını veri sinyallerine göre yorumlayın.", "satis-hunisi"],
  ["AI lead analizi", "Satış Hunisi", "Satın alma ihtimali, risk ve sonraki aksiyon önerisini üretin.", "satis-hunisi"],
  ["Gelir tahmini", "Satış Hunisi", "Teklif tutarlarını aşama olasılıklarıyla ağırlıklandırarak değerlendirin.", "satis-hunisi"],
  ["Lead müşteriye dönüştürme", "Satış Hunisi", "Kazanılan lead için duplicate kontrolüyle müşteri ve onboarding görevleri oluşturun.", "satis-hunisi"],
  ["Lead arşivleme", "Satış Hunisi", "Leadleri hard delete kullanmadan arşivleyip CRM üzerinden geri yükleyin.", "satis-hunisi"],
  ["Tahsilat ekleme", "Tahsilat & Karlılık", "Müşteri, tutar, vade, hizmet dönemi ve görünürlük bilgisiyle ödeme kaydı oluşturun.", "tahsilat"],
  ["Ödemeyi tahsil edildi işaretleme", "Tahsilat & Karlılık", "Bekleyen ödemeyi ödeme tarihiyle birlikte kapatın.", "tahsilat"],
  ["Vadesi geçen ödemeler", "Tahsilat & Karlılık", "Vade tarihi geçmiş açık tahsilatları filtreleyip takip edin.", "tahsilat"],
  ["Karlılık ekranı", "Tahsilat & Karlılık", "Gelir, gider, ödenen ve bekleyen tutar dengesini inceleyin.", "karlilik"],
  ["Tahsilat filtreleri", "Tahsilat & Karlılık", "Firma, durum, ödeme türü, ay ve yıl filtrelerini kontrollü uygulayın.", "tahsilat"],
  ["Görev oluşturma", "Görev Yönetimi", "Başlık, açıklama, öncelik, tarih ve sorumlu bilgisiyle görev açın.", "gorevler"],
  ["Görev atama", "Görev Yönetimi", "Görevi uygun ekip üyesine atayıp teslim tarihini belirleyin.", "gorevler"],
  ["Görev tamamlama ve tekrar açma", "Görev Yönetimi", "Tamamlanan görevi tarihçede koruyun veya yeniden açın.", "gorevler"],
  ["Otomatik satış görevleri", "Görev Yönetimi", "Teklif, takip ve onboarding aşamalarında üretilen görevleri yönetin.", "gorevler"],
  ["Müşteriye görünür görevler", "Görev Yönetimi", "Yalnız paylaşılması uygun görevleri müşteri paneline açın.", "gorevler"],
  ["Meta raporu oluşturma", "Raporlama Merkezi", "Meta kampanya metriklerinden dönemsel müşteri raporu hazırlayın.", "meta-analiz"],
  ["Google Ads raporu oluşturma", "Raporlama Merkezi", "Google Ads veya manuel performans verilerini raporlayın.", "google-analiz"],
  ["AI rapor yorumu", "Raporlama Merkezi", "Performans verilerinden Türkçe, ölçülü ve aksiyon odaklı yorum üretin.", "musteri-raporlari"],
  ["Executive rapor", "Raporlama Merkezi", "Teknik metrikleri müşteri dostu yönetici özetine dönüştürün.", "musteri-raporlari"],
  ["PDF Word Excel dışa aktarma", "Raporlama Merkezi", "Türkçe karakterleri koruyan rapor dosyalarını indirin.", "musteri-raporlari"],
  ["Meta Pixel kurulumu", "Meta Entegrasyonları", "Müşteri Pixel ID bilgisini kaydedip ölçümleme durumunu kontrol edin.", "entegrasyonlar"],
  ["Conversion API kurulumu", "Meta Entegrasyonları", "Sunucuda maskeli token ile CAPI test ve durum kontrolü yapın.", "entegrasyonlar"],
  ["Meta Test Event", "Meta Entegrasyonları", "Test Event Code ile gerçek müşteri verisi kullanmadan olay doğrulayın.", "entegrasyonlar"],
  ["Meta reklam hesabı bağlama", "Meta Entegrasyonları", "Business, Ads Account, Facebook Page ve Instagram hesaplarını firmaya eşleyin.", "reklam-hesabi-eslestirme"],
  ["Meta veri senkronizasyonu", "Meta Entegrasyonları", "Tarih aralığı seçip kampanya ve metrik verilerini güvenli biçimde çekin.", "meta-istihbarat"],
  ["Meta sorun giderme", "Meta Entegrasyonları", "Token, yetki, hesap ID ve veri dönemi sorunlarını teşhis edin.", "sistem-test-merkezi"],
  ["Google Ads müşteri hesabı", "Google Entegrasyonları", "Google Ads Customer ID ve MCC ilişkisini müşteriyle eşleyin.", "reklam-hesabi-eslestirme"],
  ["Google Analytics GA4", "Google Entegrasyonları", "Measurement ID ve property bilgisini analitik hazırlığı için kaydedin.", "entegrasyonlar"],
  ["Search Console hazırlığı", "Google Entegrasyonları", "Site sahipliği ve organik arama veri gereksinimlerini kontrol edin.", "entegrasyonlar"],
  ["Tag Manager ve dönüşüm takibi", "Google Entegrasyonları", "Etiket ve dönüşüm olaylarının isimlendirme planını yönetin.", "entegrasyonlar"],
  ["Müşteri keşfi", "HK Intelligence", "Şehir, ilçe ve sektör bazında işletme adayları bulun.", "musteri-kesfi"],
  ["Haritalar keşfi", "HK Intelligence", "Yerel işletme sinyallerini harita ve Google profili verileriyle inceleyin.", "haritalar"],
  ["Rakip analizi", "HK Intelligence", "Rakip görünürlüğü, reklam fırsatı ve önerilen aksiyonları karşılaştırın.", "rakip-analizi"],
  ["Lead workspace", "HK Intelligence", "Keşif sonuçlarını CRM ve teklif hazırlığına taşıyın.", "lead-analizi"],
  ["AI dijital denetim", "HK Intelligence", "Web, Instagram ve Google sinyallerinden denetim özeti üretin.", "ai-denetim"],
  ["AI Studio içerik üretimi", "AI Studio", "Marka, kanal ve hedefe göre kontrollü içerik taslağı üretin.", "ai-studio"],
  ["Prompt kullanımı", "AI Studio", "Tekrar kullanılabilir promptları bağlam ve çıktı beklentisiyle çalıştırın.", "prompt-uretimi"],
  ["AI sosyal medya planı", "AI Studio", "Sektör ve hedefe göre düzenlenebilir içerik takvimi hazırlayın.", "icerik-fikirleri"],
  ["Dosya yükleme", "Dosya & Belge Merkezi", "Dosya URL, tür, açıklama ve görünürlük bilgisiyle müşteri dosyası ekleyin.", "belgeler"],
  ["Dosya paylaşımı", "Dosya & Belge Merkezi", "Yalnız güvenli ve müşteri için uygun belgeleri görünür yapın.", "belgeler"],
  ["Kreatif Merkezi", "Dosya & Belge Merkezi", "Reklam görsellerini önizleme ve indirme için kreatif merkezine ekleyin.", "belgeler"],
  ["Kullanıcı rolleri", "Kullanıcı Yönetimi", "Admin, yönetici, editör ve müşteri rollerinin sınırlarını yönetin.", "kullanici-yonetimi"],
  ["Modül yetkileri", "Kullanıcı Yönetimi", "Ekip üyelerinin yalnız ihtiyaç duyduğu modüllere erişmesini sağlayın.", "kullanici-yonetimi"],
  ["Şifre ve hesap güvenliği", "Kullanıcı Yönetimi", "Geçici şifre, aktiflik ve güvenli hesap yönetimi uygulayın.", "kullanici-yonetimi"],
  ["SMTP ayarları", "Ayarlar", "Sistem e-postalarının sunucu bağlantısı ve gönderim durumunu yönetin.", "entegrasyonlar"],
  ["WhatsApp ayarları", "Ayarlar", "WhatsApp bağlantı kimliklerini ve hazır mesaj akışlarını yönetin.", "entegrasyonlar"],
  ["AI sağlayıcı ayarları", "Ayarlar", "Auto Router, OpenAI, Gemini, Groq, Claude, Manus, OpenRouter, Ollama ve Demo/Yerel Yedek Akış seçeneklerini güvenli biçimde yapılandırın.", "entegrasyonlar"],
  ["Merkezi AI Sağlayıcı Seçici nasıl çalışır?", "HK Agent Hub", "Google İstihbarat, Meta İstihbarat, AI Studio, Teklif Motoru ve Agent Hub aynı sağlayıcı listesini kullanır; yeni sağlayıcı tek merkezden tüm modüllere yansır.", "agent-hub"],
  ["Auto Router ne zaman kullanılır?", "HK Agent Hub", "Normal kullanımda Auto Router seçilmelidir. HK Intelligence görev tipini, aktif API anahtarlarını, hız/maliyet dengesini ve yedek akışı kontrol ederek sağlayıcı seçer.", "agent-hub"],
  ["Google İstihbarat neden Auto/Gemini önerir?", "HK Agent Hub", "Google İstihbarat arama görünürlüğü, SEO ve Google ekosistemi sinyalleri ürettiği için Auto Router ilk seçenek, Gemini ikinci seçenek, OpenAI üçüncü seçenek olarak değerlendirilir.", "agent-hub"],
  ["Manus ne zaman seçilmeli?", "HK Agent Hub", "Manus kısa reklam yorumları için varsayılan değildir; rakip analizi, pazar araştırması, fiyat karşılaştırması, sektör keşfi ve uzun web araştırması için seçilmelidir.", "agent-hub"],
  ["Groq ne zaman seçilmeli?", "HK Agent Hub", "Groq hızlı ve düşük maliyetli kısa cevaplarda uygundur; detaylı Google Ads analizi veya uzun raporlar için birincil tercih değildir.", "agent-hub"],
  ["Eksik API anahtarı nasıl anlaşılır?", "HK Agent Hub", "AI sağlayıcı kartlarında Aktif, Yapılandırılmadı, Eksik endpoint, Demo veya Yerel durumu görünür; gerçek secret değerleri tarayıcıya gönderilmez.", "agent-hub"],
  ["Agent Hub nedir?", "HK Agent Hub", "ChatGPT, Claude, Gemini, Groq, Manus ve yerel/alternatif modelleri görev tipine göre yöneten AI orkestrasyon merkezini kullanın.", "agent-hub"],
  ["Manus neden varsayılan değildir?", "HK Agent Hub", "Manus günlük kısa cevaplar yerine rakip analizi, pazar araştırması, fiyat karşılaştırması, sektör keşfi ve kapsamlı rapor görevlerinde kullanılır.", "agent-hub"],
  ["Hangi görevde hangi AI kullanılır?", "HK Agent Hub", "Reklam analizi, CRM özeti, içerik üretimi, derin araştırma ve hızlı cevap görevlerinin sağlayıcı önceliğini okuyun.", "agent-hub"],
  ["Agent Hub API key yönetimi", "HK Agent Hub", "Production’da API anahtarlarını Vercel Project Settings > Environment Variables alanına ekleyin; anahtarlar frontend’e gönderilmez.", "agent-hub"],
  ["Agent Hub yedek akış mantığı", "HK Agent Hub", "Bir sağlayıcı pasif, hatalı veya yapılandırılmamışsa sıradaki sağlayıcıya geçiş ve demo/yerel yedek akış davranışını kontrol edin.", "agent-hub"],
  ["İşlem kayıtları nasıl okunur?", "HK Agent Hub", "Görev tipi, seçilen sağlayıcı, durum, süre, tahmini maliyet, işlem metni ve hata alanlarıyla agent çalışmalarını denetleyin.", "agent-hub"],
  ["Agent maliyet takibi", "HK Agent Hub", "Bugünkü görev, aylık görev, tahmini maliyet, başarı oranı ve Manus derin araştırma sayısını takip edin.", "agent-hub"],
  ["Auto Router nasıl seçim yapar?", "HK Agent Hub", "Görev tipi, maliyet, sağlayıcı durumu, veri ihtiyacı ve yedek akışa göre OpenAI, Gemini, Claude, Groq, Manus veya demo sağlayıcıyı otomatik seçin.", "agent-hub"],
  ["AI seçim nedeni nasıl okunur?", "HK Agent Hub", "Run sonucundaki AI Seçim Nedeni kartında seçilen sağlayıcıyı, neden seçildiğini, kullanılmayan sağlayıcıları, eksik API anahtarlarını ve önerilen düzeltmeyi okuyun.", "agent-hub"],
  ["Manuel AI seçimi nasıl çalışır?", "HK Agent Hub", "Kullanıcı Groq, Gemini, OpenAI veya başka bir sağlayıcıyı elle seçerse sistem önce kesinlikle o sağlayıcıyı dener. Başarısız olursa yedek akışa geçer ve nedenini açıkça yazar.", "agent-hub"],
  ["Auto Router ne zaman devreye girer?", "HK Agent Hub", "Auto Router yalnız Otomatik Seçim seçildiğinde karar verir. Manuel seçimde router (yönlendirici) sadece öneri ve uyarı üretir, seçimi sessizce değiştirmez.", "agent-hub"],
  ["Groq seçilince neden başka sağlayıcı kullanılabilir?", "HK Agent Hub", "Groq manuel seçilmişse ilk deneme Groq ile yapılır. GROQ_API_KEY eksikse veya API hata verirse Demo/Yerel Yedek Akış kullanılır ve kartta seçilen sağlayıcı ile kullanılan sağlayıcı ayrı gösterilir.", "agent-hub"],
  ["Fallback/yedek akış nasıl okunur?", "HK Agent Hub", "Fallback (yedek akış), seçilen sağlayıcı çalışmadığında raporun bozulmaması için devreye giren güvenli alternatiftir. Kartlarda yedek akış nedeni, eksik environment değişkeni ve önerilen düzeltme görünür.", "agent-hub"],
  ["Sağlayıcı sağlık paneli nasıl yorumlanır?", "HK Agent Hub", "Sağlayıcı Sağlığı bölümünde health check (sağlık kontrolü), latency (yanıt süresi), hata sayısı, başarı oranı, tahmini maliyet ve Auto Router skoru izlenir.", "agent-hub"],
  ["Maliyet ve hata oranları ne anlama gelir?", "HK Agent Hub", "Maliyet tahmini token (işlem metni) ve sağlayıcı fiyat varsayımıyla hesaplanır. Hata oranı son 24 saatte başarısız veya yedek akışa düşen görevleri gösterir.", "agent-hub"],
  ["HK Intelligence Orchestrator nedir?", "HK Agent Hub", "HK Intelligence Orchestrator, sağlayıcı çıktısını son karar katmanı olarak düzenler; çelişkileri ayıklar, garanti vermeyen Türkçe rapor dili kullanır ve 7 günlük aksiyon planı üretir.", "agent-hub"],
  ["Çoklu AI işbirliği nasıl çalışır?", "HK Agent Hub", "Derin araştırma, pazar analizi, teklif üretimi ve müşteri raporlarında birden fazla sağlayıcının çıktısını HK Intelligence final raporunda birleştirin.", "agent-hub"],
  ["HK Intelligence final layer ne yapar?", "HK Agent Hub", "Sağlayıcı çıktısını doğrudan göstermeden yönetici özeti, bulgular, riskler, fırsatlar, aksiyonlar, 7 günlük plan ve müşteri mesajına dönüştürür.", "agent-hub"],
  ["Scheduled agent görevleri nasıl kurulur?", "HK Agent Hub", "Günlük, haftalık veya aylık agent görevleri oluşturup cron-ready endpoint ile güvenli şekilde çalıştırılacak hazırlığı yapın.", "agent-hub"],
  ["Agent Hub çıktı hazırlama ve e-posta taslakları", "HK Agent Hub", "Agent sonucundan Word, PDF, PowerPoint hazırlık verisi ve müşteriye gönderilebilir e-posta taslağı üretin.", "agent-hub"],
  ["Gerçek AI sağlayıcıları nasıl çalışır?", "HK Agent Hub", "OpenAI, Gemini, Groq, Claude, OpenRouter, Ollama ve Manus API anahtarı varsa server-side gerçek çağrı yapar; yoksa güvenli demo/yedek akış üretir.", "agent-hub"],
  ["Agent Memory nedir?", "HK Agent Hub", "Müşteri bazlı geçmiş agent sonuçları, öneriler ve uygulanmış aksiyonları saklayarak sonraki analizlere bağlam sağlar.", "agent-hub"],
  ["Maliyet paneli nasıl okunur?", "HK Agent Hub", "Bugünkü ve aylık tahmini maliyeti, sağlayıcı bazlı maliyeti, ortalama görev maliyetini ve yedek akış oranını kontrol edin.", "agent-hub"],
  ["Queue ne işe yarar?", "HK Agent Hub", "Uzun süren agent görevlerini sırada, çalışıyor, başarısız veya iptal edildi durumlarıyla izleyin; gerekirse tekrar çalıştırın veya iptal edin.", "agent-hub"],
  ["Export dosyaları nasıl üretilir?", "HK Agent Hub", "PDF için print-ready HTML, Word için metin/markdown, PowerPoint için slayt taslağı hazırlanır; bozuk indirme linki gösterilmez.", "agent-hub"],
  ["E-posta ve WhatsApp raporları nasıl kullanılır?", "HK Agent Hub", "Final rapordan müşteri e-posta taslağı, onaylı gönderim ve WhatsApp’a uygun kısa özet üretin; müşteri e-postası yoksa sistem uyarır.", "agent-hub"],
  ["Entegrasyon Kontrolü nasıl kullanılır?", "HK Agent Hub", "OpenAI, Gemini, Groq, Claude, OpenRouter, Manus, Ollama, Resend, Discord, Meta, Google Ads, Supabase ve Cron Secret durumlarını secret göstermeden kontrol edin.", "agent-hub"],
  ["Slack neden kaldırıldı?", "HK Agent Hub", "Agent Hub içinde Slack bildirimi kullanıcı arayüzünden kaldırıldı; bildirim için sade ve tek akış olarak Discord Webhook desteklenir.", "agent-hub"],
  ["Discord nasıl bağlanır?", "HK Agent Hub", "Discord bildirimi için DISCORD_WEBHOOK_URL değerini Vercel Environment Variables alanına ekleyin; yoksa Discord butonu gizlenir.", "agent-hub"],
  ["Sonuç nasıl kaydedilir?", "HK Agent Hub", "Sonucu Kaydet butonu agent_runs kaydını saved_at, saved_by ve saved_title alanlarıyla işaretler ve Agent Kayıtları içinde saklar.", "agent-hub"],
  ["AI Hafızasına kaydetme ne işe yarar?", "HK Agent Hub", "AI Hafızasına Kaydet butonu analiz özetini, aksiyonları ve riskleri agent_memories tablosuna müşteri bağlamı olarak kaydeder.", "agent-hub"],
  ["Training Center nasıl kullanılır?", "HK Agent Hub", "HK Intelligence’ın garanti vermeyen dil, sade müşteri açıklaması, risk anlatımı ve 7 günlük plan kurallarını yönetin.", "agent-hub"],
  ["Prompt Versioning nedir?", "HK Agent Hub", "Prompt sürümlerini saklayın, değişiklik notu ekleyin ve gerektiğinde eski sürüme geri dönün.", "agent-hub"],
  ["Benchmark nasıl yapılır?", "HK Agent Hub", "Aynı promptu birden fazla AI sağlayıcısına verip süre, maliyet, güven skoru ve HK Intelligence kararını karşılaştırın.", "agent-hub"],
  ["Meta/Google veri kaynakları Agent Hub’a nasıl bağlanır?", "HK Agent Hub", "Müşteri seçildiğinde mevcut Meta, Google, reklam raporu ve manuel kayıtlar prompt bağlamına veri kaynağı olarak eklenebilir; veri yoksa açıkça eksik veri yazılır.", "agent-hub"],
  ["Agent Hub Vercel env listesi", "HK Agent Hub", "Production’da OPENAI_API_KEY, GEMINI_API_KEY, GROQ_API_KEY, ANTHROPIC_API_KEY, OPENROUTER_API_KEY, MANUS_API_KEY, MANUS_API_BASE_URL, MANUS_API_ENDPOINT, OLLAMA_BASE_URL, AGENT_HUB_CRON_SECRET, SMTP/RESEND ve DISCORD_WEBHOOK_URL değerlerini Vercel Environment Variables alanına ekleyin.", "agent-hub"],
  ["Müşterilere direkt erişim", "CRM & Müşteriler", "Admin panelde Müşteriler öğesini Müşteri & Satış grubunun ilk sırasında ve dashboard hızlı aksiyonlarında bulun.", "musteriler"],
  ["Admin buton okunabilirliği standardı", "Ayarlar", "Siyah/dark primary butonlar yerine açık temada okunur cyan, amber, blue veya border tabanlı admin buton stillerini kullanın.", "sistem-rehberi"],
  ["Sistem ayarları", "Ayarlar", "Performans, güvenlik, yedekleme ve uygulama tercihlerini yönetin.", "sistem-ayarlari"],
  ["Butonlar ve İşlem Mantığı", "Ayarlar", "Kaydetme, güncelleme, arşivleme, hata bildirimi ve kalıcılık davranışlarını doğrulayın.", "sistem-test-merkezi"],
  ["Logo ve marka yönetimi", "Web Site Yönetimi", "Public site logo, favicon ve marka metinlerini güncelleyin.", "web-sitesi-yonetimi"],
  ["Hizmet ve paket yönetimi", "Web Site Yönetimi", "Public sitedeki hizmet ve paket içeriklerini düzenleyin.", "web-sitesi-yonetimi"],
  ["İletişim ve sosyal bağlantılar", "Web Site Yönetimi", "Telefon, e-posta, adres ve sosyal medya bağlantılarını yönetin.", "web-sitesi-yonetimi"],
  ["Müşteri panelinde raporlar", "Müşteri Paneli", "Yayınlanmış ve görünür raporları müşteri gözüyle kontrol edin.", "musteriler"],
  ["Müşteri panelinde ödeme ve görevler", "Müşteri Paneli", "Yalnız görünür ödeme ve görev kayıtlarının doğru yansıdığını doğrulayın.", "musteriler"],
  ["Müşteri panelinde dosyalar", "Müşteri Paneli", "Paylaşılan belge ve kreatiflerin açılma ve indirme akışını kontrol edin.", "musteriler"],
  ["Pixel çalışmıyor", "Sorun Giderme", "Pixel ID, public sayfa kapsamı ve Events Manager test durumunu kontrol edin.", "sistem-test-merkezi"],
  ["Meta verisi gelmiyor", "Sorun Giderme", "Token, reklam hesabı, tarih aralığı ve yetki hatalarını sırasıyla inceleyin.", "sistem-test-merkezi"],
  ["Google Ads bağlanmıyor", "Sorun Giderme", "Customer ID, MCC, OAuth ve API yapılandırmasını doğrulayın.", "sistem-test-merkezi"],
  ["Müşteri giriş yapamıyor", "Sorun Giderme", "Kullanıcının aktifliği, firma bağı ve rolünü kontrol edin.", "kullanici-yonetimi"],
  ["Rapor veya export görünmüyor", "Sorun Giderme", "Rapor durumu, müşteri görünürlüğü ve dosya üretim sonucunu kontrol edin.", "musteri-raporlari"],
  ["Görev veya ödeme görünmüyor", "Sorun Giderme", "Arşiv, tarih, müşteri ve görünürlük filtrelerini kontrol edin.", "sistem-test-merkezi"],
  ["AI çalışmıyor", "Sorun Giderme", "Aktif sağlayıcı, model, API anahtarı ve demo yedek akış durumunu kontrol edin.", "sistem-test-merkezi"],
  ["Admin modülleri ve bakım yapısı", "Ayarlar", "AdminDashboard içindeki büyük modüllerin küçük bileşenlere nasıl ayrıldığını ve QA performans uyarılarının nasıl yorumlanacağını öğrenin.", "sistem-rehberi"],
  ["QA Center nasıl kullanılır?", "Ayarlar", "Sayfa, API, migration, env, güvenlik ve buton risklerini tek QA ekranından tarayın.", "qa-center"],
  ["HK Reklam Doktoru Pro nasıl yorumlanır?", "Raporlama Merkezi", "Reklam sağlık skoru, doktor teşhisleri, reçete aksiyonları, kreatif yorgunluğu ve müşteri özetini birlikte okuyun.", "ad-insights"],
  ["Görev şablonları nasıl kullanılır?", "Görev Yönetimi", "Onboarding, Pixel, rapor, teklif takip ve tahsilat hatırlatma görevlerini hazır şablondan oluşturun.", "musteriler"],
  ["Tekrarlayan görev nasıl oluşturulur?", "Görev Yönetimi", "Günlük, haftalık, aylık veya özel tekrar kuralı ile düzenli operasyon görevleri planlayın.", "musteriler"],
  ["Alt görev nedir?", "Görev Yönetimi", "Büyük işleri küçük kontrol maddelerine bölerek ana görevin altında takip edin.", "musteriler"],
  ["Reklam sağlık skoru ne anlama gelir?", "Raporlama Merkezi", "CTR, CPC, CPM, lead/mesaj sinyali, frekans ve bütçe verimliliğinden oluşan 0-100 performans puanını yorumlayın.", "ad-insights"],
  ["Boşa harcanan bütçe nasıl yorumlanır?", "Raporlama Merkezi", "Düşük CTR veya yüksek CPC sinyali veren reklam harcamasını durdurma, izleme veya kreatif yenileme kararı için kullanın.", "ad-insights"],
  ["Yeni menü kategorizasyonu", "Ayarlar", "Kontrol Merkezi, Müşteri & Satış, Ajans Operasyonu, Reklam & Raporlama, İçerik & AI, Entegrasyonlar, Araçlar & Yardım ve Ayarlar kategorilerini doğru okuyun.", "sistem-rehberi"],
  ["Müşteri & Satış akışı", "Müşteri & Satış", "Müşteri keşfinden CRM, fırsat pipeline, teklif, takip ve kazanıldı/kaybedildi analizine kadar satış yolunu yönetin.", "musteri-kesfi"],
  ["Ajans Operasyonu akışı", "Ajans Operasyonu", "Görevler, takvim, tahsilat, onboarding ve ajans hedeflerini günlük operasyon planına bağlayın.", "gorevler"],
  ["Teklif Takip Merkezi", "Müşteri & Satış", "Teklif gönderimi sonrası 3, 7, 14 ve 21 günlük takip akışlarını izleyin ve hızlı mesajları kopyalayın.", "teklif-takip-merkezi"],
  ["Takip kuralları", "Müşteri & Satış", "Tekliften 3 gün sonra ilk takip, 7 gün sonra ikinci takip, 14 gün sonra son takip ve 21 gün sonra pasif değerlendirme kuralını uygulayın.", "teklif-takip-merkezi"],
  ["Kazanıldı / Kaybedildi Analizi", "Müşteri & Satış", "Kapanan fırsatlardan sektör, şehir, paket, bütçe ve itiraz öğrenimi çıkarın.", "kazanildi-kaybedildi-analizi"],
  ["AI Satış Koçu", "İçerik & AI", "Lead veya fırsat için arama metni, WhatsApp mesajı, e-posta taslağı, itiraz cevabı ve kapanış cümlesi üretin.", "ai-satis-kocu"],
  ["Müşteri segmentleri", "Müşteri & Satış", "Sıcak lead, teklif bekliyor, takipte, pasif, kazanıldı, kaybedildi ve tahsilat riski segmentlerini yorumlayın.", "lead-workspace"],
  ["Tahsilat + onboarding görevleri", "Ajans Operasyonu", "Kazanılan fırsat sonrası ilk ödeme, sözleşme, reklam erişimleri, Pixel, Analytics, içerik ve ilk rapor görevlerini oluşturun.", "gorevler"],
  ["Ajans Hedef Panosu", "Ajans Operasyonu", "Aylık gelir, müşteri, teklif, görüşme ve tahsilat hedeflerini takip edip hedefe kalan aksiyonu belirleyin.", "ajans-hedefleri"],
  ["Gerçek / Tahmini / Eksik veri etiketleri", "Dashboard & Kontrol Merkezi", "Karar panellerinde verinin gerçek kayıttan mı, tahminden mi yoksa eksik bilgiden mi geldiğini kontrol edin.", "qa-center"],
  ["Mobil Operasyon Modu gelişmiş kullanım", "Ayarlar", "Saha kullanımında büyük buton, tek sütun kart ve kolay basılabilir aksiyon düzenini açıp kapatın.", "mobil-operasyon-modu"],
  ["Migration sonrası Supabase kontrolü", "Ayarlar", "Yeni migration çalıştırıldıktan sonra PostgREST schema cache yenileme ve QA Merkezi kontrollerini doğrulayın.", "qa-center"]
];

function slugify(value: string) {
  return value.toLocaleLowerCase("tr").normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/ı/g, "i").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

export const systemGuideSeeds: SystemGuideSeed[] = definitions.map(([title, category, description, route]) => ({
  slug: slugify(title),
  title,
  category,
  description,
  route: route ? `/hk-admin/${route}` : "/hk-admin",
  content: {
    purpose: description,
    whenToUse: `${title} işlemini uygulamanız veya ilgili kaydın doğru çalıştığını doğrulamanız gerektiğinde kullanılır.`,
    steps: [
      `${route ? `/hk-admin/${route}` : "/hk-admin"} ekranını yetkili hesabınızla açın.`,
      `${description} İlgili müşteri veya kaydı seçip mevcut bilgileri kontrol edin.`,
      "Değişiklikleri kaydetmeden önce görünürlük, tarih ve durum alanlarını doğrulayın; işlem sonucunu üst bildirimden kontrol edin."
    ],
    example: `${title} sırasında örnek bir kayıt üzerinde işlem yapın; kaydetme sonrasında listeyi yenileyerek sonucun kalıcı olduğunu doğrulayın.`,
    commonErrors: ["Yanlış müşteri veya tarih filtresiyle işlem yapmak.", "Kaydetmeden ekrandan ayrılmak ya da görünürlük alanını kontrol etmemek."],
    tips: ["Önce filtreleri temizleyip doğru kaydı seçin.", "Kritik değişikliklerden sonra ilgili müşteri panelini veya raporu kontrol edin."],
    warnings: ["Token, API anahtarı, dahili not veya müşteri için gizli bilgileri paylaşılabilir alanlara yazmayın.", "Silme yerine mevcutsa arşivleme akışını tercih edin."]
  }
}));
