export type SystemGuideSeed = {
  slug: string;
  title: string;
  category: string;
  description: string;
  route: string;
  videoUrl?: string;
  content: {
    purpose: string;
    whenToUse: string;
    steps: string[];
    example: string;
    commonErrors: string[];
    tips: string[];
    warnings: string[];
  };
};

export const systemGuideCategories = [
  "Müşteri Serüveni", "Dashboard & Kontrol Merkezi", "CRM & Müşteriler", "Müşteri & Satış", "Ajans Operasyonu", "Satış Hunisi", "Tahsilat & Karlılık",
  "Görev Yönetimi", "Raporlama Merkezi", "Meta Entegrasyonları", "Google Entegrasyonları",
  "HK Intelligence", "AI Studio", "Dosya & Belge Merkezi", "Kullanıcı Yönetimi", "Ayarlar",
  "Web Site Yönetimi", "Müşteri Paneli", "Sorun Giderme", "HK Agent Hub"
];

const definitions: Array<[string, string, string, string]> = [
  ["Dashboard nedir?", "Dashboard & Kontrol Merkezi", "Ajansın günlük KPI, risk ve aksiyonlarını tek ekranda izleyin.", ""],
  ["HK Intelligence Autonomous Agency", "HK Intelligence", "HK Operating System içinde CEO, sanal ajans ekibi, risk, KPI, takvim, öneri ve final karar katmanını yöneten autonomous agency işletim sistemi.", "hk-intelligence-ceo"],
  ["HK Intelligence CEO nasıl çalışır?", "HK Intelligence", "Kullanıcının verdiği işi Google Ads AI, Meta AI, SEO AI, CRM AI, Creative AI, Reporting AI, Sales AI ve Finance AI ajanlarına dağıtır; sonucu HK Intelligence Final Layer ile tek rapora dönüştürür.", "hk-intelligence-ceo"],
  ["HK CEO Masası nasıl kullanılır?", "HK Intelligence", "CEO ekranındaki her kart artık detay modalı, ilgili modüle geçiş, hazırlık verisi kopyalama, görev oluşturma veya Agent Hub aksiyonuna bağlanır.", "hk-intelligence-ceo"],
  ["Hazır paketler nasıl üretilir?", "HK Intelligence", "Hazır Paketler bölümünde sektör kartlarından Komut Metni Üret, İş Akışı Üret, AI Ekibi Kur, KPI Şablonu ve Rapor Şablonu aksiyonlarını çalıştırın.", "hk-intelligence-ceo"],
  ["Yeni paket nasıl oluşturulur?", "HK Intelligence", "Yeni Paket Üret butonunda sektör, hedef müşteri, hizmetler, bütçe aralığı, ana hedef, kanallar ve çıktı tipini girerek komut metni, iş akışı, AI ekibi, KPI, operasyon planı, teklif ve rapor başlıkları üretin.", "hk-intelligence-ceo"],
  ["Paket Pazarı nedir?", "HK Intelligence", "Paket Pazarı, sabit sektör paketlerini ve AI ile üretilen kullanıcı paketlerini tek yerde toplar; paketler komut metni, iş akışı, AI ekibi, KPI, rapor, teklif ve operasyon planı içerir.", "hk-intelligence-ceo"],
  ["Hazır paket ile benim paketlerim farkı nedir?", "HK Intelligence", "Hazır Paketler sabit sektör başlangıç paketleridir; Benim Paketlerim ise kullanıcının AI Destekli Yeni Paket Üret formuyla oluşturup kaydettiği özel sektör paketleridir.", "hk-intelligence-ceo"],
  ["AI ile yeni paket nasıl üretilir?", "HK Intelligence", "AI Destekli Yeni Paket Üret formunda sektör, niş, hedef müşteri, bölge, hedef, kanallar, reklam bütçesi, hizmet bedeli, rekabet seviyesi, teklif dili ve süre bilgilerini girip AI ile Paketi Üret butonunu kullanın.", "hk-intelligence-ceo"],
  ["AI ile paket nasıl üretilir?", "HK Intelligence", "Paket Pazarı içinde AI ile Otomatik Doldur modunu seçin; sektör, niş, bölge, hedef müşteri, ana hedef, bütçe, hizmet bedeli, rekabet seviyesi ve ek notları girip AI ile Doldur butonuyla paket adı, strateji, sosyal medya planı, reklam planı, KPI, teklif ve 7/30/90 günlük büyüme planı üretin.", "hk-intelligence-ceo"],
  ["Manuel paket ile AI paket farkı nedir?", "HK Intelligence", "Manuel modda alanları ekip kendisi doldurur ve Paketi Önizle ile yerel şablon üretir; AI modunda HK Intelligence sektör bağlamından komut metni, iş akışı, sosyal medya içerik takvimi, onay akışı, kampanya operasyonu, rapor ve teklif taslağını otomatik doldurur.", "hk-intelligence-ceo"],
  ["Şube nasıl eklenir?", "CRM & Müşteriler", "Müşteri profil popup içindeki Şubeler bölümünden Şube Ekle aksiyonunu kullanın; şube adı, şehir, ilçe, adres, telefon, WhatsApp, e-posta, Google Maps URL, landing page, Meta/Google/GA4/GTM ve sorumlu kişi bilgilerini tamamlayın.", "hk-intelligence-ceo"],
  ["Şube bazlı analiz nasıl yapılır?", "CRM & Müşteriler", "Müşteri profilindeki Şubeler bölümünde ilgili şubeden Şube İçin Agent Analizi veya Şube Raporu Oluştur aksiyonunu kullanın. Paket uygulama sihirbazında müşteri seçildikten sonra Tüm şubeler ya da belirli şube seçilerek analiz bağlamı netleştirilir.", "hk-intelligence-ceo"],
  ["QA Center uyarıları nasıl okunur?", "Sorun Giderme", "QA Center her bulgu için sorun başlığı, nerede olduğu, ne anlama geldiği, risk seviyesi, kullanıcı etkisi, teknik sebep ve önerilen çözümü gösterir. Uyarı sistemin çöktüğü anlamına gelmez; hangi alanın güçlendirilmesi gerektiğini belirtir.", "qa-center"],
  ["Handler sinyali zayıf buton ne demek?", "Sorun Giderme", "Bu uyarı, butonun ekranda göründüğü ama tıklanınca gerçek işlem başlatıp başlatmadığının statik analizle netleşmediği anlamına gelir. Butona gerçek handler, submit davranışı veya pasif olma açıklaması eklenmelidir.", "qa-center"],
  ["Migration uyarısı ne demek?", "Sorun Giderme", "Kodun beklediği tablo veya kolon migration dosyalarında tam görünmediğinde migration uyarısı oluşur. Canlı Supabase SQL Editor’da ilgili idempotent SQL çalıştırılmadıysa kayıt işlemleri schema cache hatası verebilir.", "qa-center"],
  ["Secret sızıntı kontrolü ne demek?", "Sorun Giderme", "API key, token, secret, private key ve refresh token değerlerinin client component veya public response içinde dönmemesi kontrol edilir. Endpointler yalnız hazır/eksik, maskeli veya boolean durum döndürmelidir.", "qa-center"],
  ["Rapor payload ne demek?", "Raporlama Merkezi", "Rapor payload, ekran görüntüsü yerine rapor adı, müşteri, dönem, yönetici özeti, tablo, bulgu, risk, fırsat, aksiyon ve 7 günlük plan gibi yapısal rapor verisidir. PDF/Word/HTML/CSV çıktıları bu veriden hazırlanır.", "qa-center"],
  ["QA sonrası hangi sırayla onarım yapılır?", "Sorun Giderme", "Önce Kritik ve Güvenlik bulguları, sonra Migration ve UI/UX aksiyonları, ardından Raporlama, Agent Hub ve Teknik borç başlıkları ele alınır. QA Center’daki Onarım Planı bu sıralamayı kategori bazında gösterir.", "qa-center"],
  ["Şube bazlı filtreleme nasıl yapılır?", "CRM & Müşteriler", "Müşteri seçimi yapılan akışlarda önce müşteri, sonra Tüm şubeler veya ilgili şube seçilir. Şube seçildiğinde paket uygulama, rapor, görev ve analiz bağlamı o şubeye göre hazırlanır.", "hk-intelligence-ceo"],
  ["Şubeye paket nasıl uygulanır?", "HK Intelligence", "Paket Pazarı > Müşteriye Uygula sihirbazında müşteriyi seçin, şube alanından Tüm şubeler veya belirli şubeyi seçin, uygulanacak varlıkları işaretleyin ve Paketi Uygula ile branch_id bilgisi uygulama kaydına yazılsın.", "hk-intelligence-ceo"],
  ["Sosyal medya içerik takvimi nasıl kullanılır?", "Ajans Operasyonu", "AI paket üretici sosyal medya planı ve içerik takvimi üretir; post, Reels, Story, kampanya çağrısı ve güven içerikleri haftalık operasyon planına bağlanır.", "hk-intelligence-ceo"],
  ["Onay akışı ne işe yarar?", "Ajans Operasyonu", "İç brief, kreatif taslak, iç onay, müşteri onayı, revize, yayına hazır ve yayınlandı adımlarıyla sosyal medya ve reklam içerikleri kontrollü ilerler.", "hk-intelligence-ceo"],
  ["Kampanya operasyon takibi nasıl yapılır?", "Ajans Operasyonu", "Paketin kampanya operasyon planı; kurulum, Pixel/Dataset, GA4, bütçe, hedef kitle, kreatif, ilk 72 saat kontrolü ve 7 günlük optimizasyon adımlarını listeler.", "hk-intelligence-ceo"],
  ["Müşteri iletişim planı nasıl takip edilir?", "CRM & Müşteriler", "Paketlerde ilk arama, teklif, sözleşme, kurulum bilgilendirmesi, haftalık rapor, aylık değerlendirme ve yenileme görüşmesi iletişim planı olarak üretilir.", "hk-intelligence-ceo"],
  ["Ajans operasyon özeti nasıl okunur?", "CRM & Müşteriler", "Müşteri profil popup içindeki Ajans Operasyon Özeti uygulanan paket, şube, aktif görev, bekleyen rapor, eksik entegrasyon ve sonraki 7 gün planını tek bakışta gösterir.", "hk-intelligence-ceo"],
  ["Hazır paket nasıl uygulanır?", "HK Intelligence", "HK CEO Hazır Paketler içinde Müşteriye Uygula butonuyla paketi seçin, aktif müşteriyi arayıp seçin, oluşturulacak kayıtları işaretleyin, önizlemeyi kontrol edin ve Paketi Uygula ile işlemi tamamlayın.", "hk-intelligence-ceo"],
  ["Paket müşteriye uygulandıktan sonra ne olur?", "HK Intelligence", "Uygulama sonrası operasyon paneli plan özeti, ne yapıldı kartı, oluşturulan kayıtlar, yapılacaklar, takip metrikleri, ilk 7 gün ve ilk 30 gün planını gösterir.", "hk-intelligence-ceo"],
  ["7 günlük plan ve 30 günlük plan nasıl kullanılır?", "HK Intelligence", "7 günlük plan ilk kurulum, reklam, kreatif, optimizasyon ve ara rapor adımlarını; 30 günlük plan ise haftalık kurulum, optimizasyon, iyileştirme ve yenileme önerisi sürecini takip etmek için kullanılır.", "hk-intelligence-ceo"],
  ["Takip metrikleri ne işe yarar?", "HK Intelligence", "Takip metrikleri lead, mesaj, randevu, CPL, CTR, CPC, ROAS, harcama, WhatsApp dönüşümü, Google yorumları ve web form dönüşümünün hangi kaynakta ne sıklıkla kontrol edileceğini gösterir.", "hk-intelligence-ceo"],
  ["Uygulanan plan müşteri profilinde nasıl bulunur?", "CRM & Müşteriler", "Müşteri profilindeki Uygulanan Paketler / Planlar bölümünde paket adı, uygulama tarihi, görev sayısı, takip metrikleri, 7 günlük plan ve 30 günlük plan özeti görünür.", "hk-intelligence-ceo"],
  ["Paket uygulayınca hangi kayıtlar oluşur?", "HK Intelligence", "Seçeneklere göre AI Hafızası kaydı, müşteri notu, 30 günlük görev planı, Agent Hub iş akışı taslağı, KPI şablonu, rapor şablonu ve teklif taslağı hazırlanır; işlem sonucu uygulama kaydına yazılır.", "hk-intelligence-ceo"],
  ["Paket uygulandıktan sonra hangi kayıtlar oluşur?", "HK Intelligence", "Başarı ekranında AI Hafızası, Müşteri Notu, Görevler, İş Akışı Taslağı, KPI Şablonu, Rapor Şablonu ve Teklif Taslağı kartları Türkçe durum rozetleriyle gösterilir.", "hk-intelligence-ceo"],
  ["Oluşan kayıtlar nereden kontrol edilir?", "HK Intelligence", "Sonraki Adımlar alanından Müşteri Profilini Aç, Görevleri Gör, AI Hafızasında Aç, İş Akışını Aç, Rapor Şablonunu Gör, Teklif Taslağını Gör ve Uygulama Kaydını Aç butonları kullanılır.", "hk-intelligence-ceo"],
  ["Müşteri profil popup nasıl açılır?", "CRM & Müşteriler", "HK CEO ekranındaki Müşteriyi Görüntüle ve Müşteri Profilini Aç aksiyonları, Müşteriler ekranındaki ortak CustomerProfileModal bileşenini kullanarak sayfadan çıkmadan profili açar.", "hk-intelligence-ceo"],
  ["Uygulanan Paketler bölümü ne işe yarar?", "CRM & Müşteriler", "Müşteri profilindeki Uygulanan Paketler bölümü paket adı, uygulama tarihi, durum, görev sayısı, hafıza kaydı, rapor ve teklif taslağı özetlerini gösterir.", "hk-intelligence-ceo"],
  ["AI Hafızası, görevler ve iş akışı taslağı nasıl takip edilir?", "HK Intelligence", "Paket uygulandıktan sonra AI Hafızası Agent Hub içinde, görevler Görevler ekranında, iş akışı taslakları Agent Hub iş akışı alanında ve uygulama kaydı HK CEO başarı ekranında takip edilir.", "hk-intelligence-ceo"],
  ["AI Hafızası neye yarar?", "HK Intelligence", "Hazır paket stratejisi, operasyon planı ve önerilen AI ekibi müşteri bağlamına kaydedilir; sonraki Agent Hub ve HK Intelligence analizlerinde müşterinin geçmiş strateji hafızası olarak kullanılabilir.", "hk-intelligence-ceo"],
  ["Görev taslakları nasıl oluşur?", "HK Intelligence", "Paketin 30 günlük operasyon planından entegrasyon kontrolü, Pixel/Dataset doğrulama, GA4/Search Console kontrolü, kreatif öneri seti, reklam sağlık raporu ve ilk müşteri raporu gibi 5-8 görev üretilir.", "hk-intelligence-ceo"],
  ["Müşteri profil popup nasıl kullanılır?", "CRM & Müşteriler", "HK CEO ekranında Müşteriyi Görüntüle aksiyonu sayfadan çıkmadan müşteri özetini modal içinde açar; genel bilgiler, kurulum, entegrasyon, görev, rapor ve tahsilat özetine hızlı erişim sağlar.", "hk-intelligence-ceo"],
  ["Uygulama kayıtları nerede görülür?", "HK Intelligence", "Hazır paket uygulamaları hk_marketplace_package_applications tablosunda seçenekler, özet, oluşturulan kayıt referansları, hata ve uygulayan kullanıcı bilgisiyle tutulur.", "hk-intelligence-ceo"],
  ["AI ajanları nasıl düzenlenir?", "HK Intelligence", "HK Dijital Ekibi ajan kartını açıp ajan adı, rol, durum, sağlayıcı, yetkinlik, görev, başarı oranı, maliyet ve not alanlarını düzenleyin; Agent Hub’da çalıştırın.", "hk-intelligence-ceo"],
  ["Operasyon takvimi nasıl planlanır?", "HK Intelligence", "AI Operasyon Takvimi kartlarından haftalık/aylık operasyonları açın; düzenle, bugün çalıştır, göreve dönüştür veya Agent Hub’da planla aksiyonlarını kullanın.", "hk-intelligence-ceo"],
  ["Risk ve öneriler nasıl göreve dönüştürülür?", "HK Intelligence", "Risk Merkezi ve AI Öneri Motoru kartlarında detay açın; görev oluştur, müşteri profilini aç, Agent ile analiz et, not olarak kaydet veya uygulama planı üret seçeneklerini kullanın.", "hk-intelligence-ceo"],
  ["Copilot’a hangi sorular sorulur?", "HK Intelligence", "En riskli müşteriler, bu hafta aranacaklar, kötü giden Google Ads hesapları, tahsilat öncelikleri, rapor ihtiyacı ve agent çalıştırma önerileri gibi doğal dil soruları sorun.", "hk-intelligence-ceo"],
  ["Command Palette nasıl kullanılır?", "HK Intelligence", "Komut arama kutusunda müşteri aç, görev oluştur, teklif oluştur, agent çalıştır, rapor oluştur, tahsilat ekle, QA Center, Website Analytics, Google veya Meta Intelligence komutlarını filtreleyip açın.", "hk-intelligence-ceo"],
  ["HK CEO Masası", "Dashboard & Kontrol Merkezi", "Bugünkü kritik görevler, acil riskler, reklam harcaması, tahsilatlar, leadler, AI ajanları, ROAS ve riskli müşteriyi tek executive ekranda izleyin.", "hk-intelligence-ceo"],
  ["HK Dijital Ekibi", "HK Intelligence", "CEO, Satış Müdürü, CRM Uzmanı, Google Ads Uzmanı, Meta Ads Uzmanı, SEO Uzmanı, Kreatif Direktör, Veri Analisti, Finans Yöneticisi ve Müşteri Başarı Uzmanı ajanlarının durumunu takip edin.", "hk-intelligence-ceo"],
  ["AI Operasyon Takvimi", "Ajans Operasyonu", "Pazartesi rakip analizi ve SEO kontrolünden cuma haftalık rapor ve AI öğrenme kayıtlarına kadar ajans ritmini planlayın.", "hk-intelligence-ceo"],
  ["Risk Merkezi Phase 4", "Dashboard & Kontrol Merkezi", "Pixel, Dataset, GA4, Google Ads, Meta ödeme, SSL, domain, hosting, API limiti, Search Console, Tag Manager, 404/500, robots.txt, sitemap ve Core Web Vitals risklerini kritik/orta/bilgi seviyesinde izleyin.", "hk-intelligence-ceo"],
  ["Rakip Alarm Merkezi", "HK Intelligence", "Rakip reklam açtı, yeni kampanya, fiyat değişimi, web sitesi değişimi, sosyal medya büyümesi ve Google yorum artışı sinyallerini özetleyin.", "hk-intelligence-ceo"],
  ["AI Kreatif Stüdyosu Phase 4", "AI Studio", "Instagram, Facebook, Google Display, Carousel, Story, Reels, TikTok, YouTube Shorts, Banner, Thumbnail, Blog, Mail, WhatsApp ve SMS üretimini prompt göstermeden başlatın.", "hk-intelligence-ceo"],
  ["AI Satış Asistanı Phase 4", "Müşteri & Satış", "Lead gelince arama metni, WhatsApp, teklif, toplantı, takip görevi ve CRM güncelleme akışını tek satış asistanı üzerinden yönetin.", "hk-intelligence-ceo"],
  ["Ajans KPI Merkezi", "Tahsilat & Karlılık", "MRR, ARR, churn, LTV, CAC, ROI, ROAS, müşteri başı kâr, aktif/pasif/riskli müşteri, tahsil edilmeyen ve beklenen gelir kartlarını yorumlayın.", "hk-intelligence-ceo"],
  ["HK Öğrenme Merkezi", "HK Intelligence", "Başarılı reklam, kreatif, hedef kitle, teklif ve satış süreçlerini AI Hafızası ile öğrenme sinyali olarak sonraki müşterilere bağlayın.", "hk-intelligence-ceo"],
  ["Dijital İkiz", "CRM & Müşteriler", "Her müşteri için son 12 ay Google, Meta, SEO, CRM, rapor, kreatif, açılış sayfası, rakip, tahsilat, toplantı, not ve yapılan işleri tek AI müşteri ikizinde analiz edin.", "hk-intelligence-ceo"],
  ["Hazır AI paketleri", "HK Intelligence", "Emlak, Klinik, Oto Galeri, Nail Studio, Diş Kliniği, Cafe, Restoran, Kuaför, Avukat ve Muhasebeci paketlerini komut metni, iş akışı, AI ekibi, dashboard (kontrol paneli), KPI ve rapor şablonuyla kullanın.", "hk-intelligence-ceo"],
  ["Çok şubeli müşteri yapısı", "CRM & Müşteriler", "Bir müşterinin birden fazla şubesini ayrı reklam, rapor, AI ve KPI ile ama tek panel altında yönetin.", "hk-intelligence-ceo"],
  ["AI Yardımcı Sohbet", "HK Intelligence", "Bu ay en çok kazandıran müşteri, kötü giden Google Ads hesapları, teklif hazırlama, Pixel kontrolü ve haftalık arama listesi gibi doğal dil sorularını HK Intelligence ile yanıtlayın.", "hk-intelligence-ceo"],
  ["Akıllı Komut Merkezi", "Dashboard & Kontrol Merkezi", "Ctrl/Cmd+K mantığıyla müşteri açma, firma arama, görev/teklif/kampanya/rapor/tahsilat oluşturma ve sistem rehberi/QA/AI/Analytics ekranlarına gitme komutlarını çalıştırın.", "hk-intelligence-ceo"],
  ["Genel Arama Phase 4", "Dashboard & Kontrol Merkezi", "Müşteri, firma, görev, belge, rapor, tahsilat, kampanya, komut metni, AI Hafızası, AI eğitimi, işlem kaydı, iş akışı, karşılaştırmalı test ve notları kategori bazlı arayın.", "hk-intelligence-ceo"],
  ["Akıllı Bildirim Merkezi", "Dashboard & Kontrol Merkezi", "Bilgi, başarı, uyarı, kritik, AI önerisi, müşteri, tahsilat, reklam, SEO, Google, Meta ve AI bildirimlerini okunabilir, arşivlenebilir ve filtrelenebilir şekilde yönetin.", "hk-intelligence-ceo"],
  ["Sağlık Merkezi Phase 4", "Sorun Giderme", "Veritabanı, Supabase, depolama, zamanlanmış işler, görev sırası, API, AI sağlayıcıları, Meta API, Google Ads API, GA4, Search Console, SMTP, Resend, Discord, web sitesi, SSL, domain ve hosting sağlıklarını izleyin.", "hk-intelligence-ceo"],
  ["AI Cost Center Phase 4", "HK Agent Hub", "OpenAI, Claude, Gemini, Groq, OpenRouter, Manus ve Ollama için toplam işlem metni, istek, başarı, hata, tahmini maliyet ve ortalama yanıt süresini takip edin.", "hk-intelligence-ceo"],
  ["Yedekleme Merkezi Phase 4", "Ayarlar", "Otomatik günlük, haftalık, aylık yedek, tek tıkla tam yedek, yedek doğrulama, yedek karşılaştırma, geri yükleme, içe/dışa aktarma kayıtları ve içerik özetlerini yönetin.", "veri-aktarma"],
  ["Müşteri Zaman Çizelgesi", "CRM & Müşteriler", "Müşteri oluşturuldu, ilk görüşme, teklif, sözleşme, ödeme, Pixel, GA4, Search Console, Google Ads, Meta, kampanya, rapor, tahsilat, toplantı, AI analiz, not ve görev olaylarını kronolojik izleyin.", "hk-intelligence-ceo"],
  ["AI Öneri Motoru", "HK Intelligence", "Remarketing, açılış sayfası, SEO, bütçe artışı/azaltışı, WhatsApp kampanyası, blog, video ve Reels önerilerini beklenen etki, zorluk, süre, maliyet ve başarı olasılığıyla okuyun.", "hk-intelligence-ceo"],
  ["HK Intelligence Command Center", "Dashboard & Kontrol Merkezi", "Tahsilat, lead, teklif, görev, müşteri ve entegrasyon sinyallerini günlük öncelik sırasına dönüştürün.", "intelligence-command-center"],
  ["Risk Merkezi", "Dashboard & Kontrol Merkezi", "Operasyon risklerini etki ve aciliyet puanına göre inceleyip ilgili kayda ilerleyin.", "risk-merkezi"],
  ["Müşteri yaşam döngüsü", "CRM & Müşteriler", "Lead aşamasından referansa kadar her müşterinin operasyon evresini izleyin.", "intelligence-command-center"],
  ["Müşteri sağlık ve kârlılık analizi", "Tahsilat & Karlılık", "Tahsilat, görev, temas, rapor ve maliyet sinyallerinden müşteri riskini ve tahmini kârlılığı okuyun.", "intelligence-command-center"],
  ["KPI kartlarını okuma", "Dashboard & Kontrol Merkezi", "Gelir, tahsilat, müşteri, kampanya ve görev kartlarını doğru yorumlayın.", ""],
  ["Kritik görevleri yönetme", "Dashboard & Kontrol Merkezi", "Geciken ve kritik görevleri önceliklendirip ilgili kayda ilerleyin.", "gorevler"],
  ["Hızlı işlemler", "Dashboard & Kontrol Merkezi", "Müşteri, kampanya, görev, tahsilat ve rapor formlarını doğrudan açın.", ""],
  ["Müşteri oluşturma", "CRM & Müşteriler", "Yeni firma profilini iletişim ve sektör bilgileriyle kaydedin.", "musteriler"],
  ["Müşteri düzenleme", "CRM & Müşteriler", "Firma, iletişim ve operasyon bilgilerini güvenli biçimde güncelleyin.", "musteriler"],
  ["Müşteri arşivleme ve geri yükleme", "CRM & Müşteriler", "Aktif olmayan müşterileri kalıcı silmeden arşivleyin ve gerektiğinde geri alın.", "musteriler"],
  ["Müşteri görünürlük ayarları", "CRM & Müşteriler", "Müşteri panelinde hangi rapor, ödeme, görev ve dosyanın görüneceğini yönetin.", "musteriler"],
  ["Müşteri paneli kullanıcısı oluşturma", "CRM & Müşteriler", "Firmaya bağlı güvenli müşteri hesabı ve panel erişimi oluşturun.", "kullanici-yonetimi"],
  ["Lead oluşturma ve düzenleme", "Satış Hunisi", "Potansiyel müşteriyi iletişim, sektör, skor ve takip bilgileriyle yönetin.", "satis-hunisi"],
  ["Kanban drag & drop", "Satış Hunisi", "Lead kartlarını onaylı sürükle-bırak akışıyla aşamalar arasında taşıyın.", "satis-hunisi"],
  ["Lead skorlama", "Satış Hunisi", "Sıcak, ılık ve soğuk lead skorlarını veri sinyallerine göre yorumlayın.", "satis-hunisi"],
  ["AI lead analizi", "Satış Hunisi", "Satın alma ihtimali, risk ve sonraki aksiyon önerisini üretin.", "satis-hunisi"],
  ["Gelir tahmini", "Satış Hunisi", "Teklif tutarlarını aşama olasılıklarıyla ağırlıklandırarak değerlendirin.", "satis-hunisi"],
  ["Lead müşteriye dönüştürme", "Satış Hunisi", "Kazanılan lead için duplicate kontrolüyle müşteri ve onboarding görevleri oluşturun.", "satis-hunisi"],
  ["Lead arşivleme", "Satış Hunisi", "Leadleri hard delete kullanmadan arşivleyip CRM üzerinden geri yükleyin.", "satis-hunisi"],
  ["Tahsilat ekleme", "Tahsilat & Karlılık", "Müşteri, tutar, vade, hizmet dönemi ve görünürlük bilgisiyle ödeme kaydı oluşturun.", "tahsilat"],
  ["Ödemeyi tahsil edildi işaretleme", "Tahsilat & Karlılık", "Bekleyen ödemeyi ödeme tarihiyle birlikte kapatın.", "tahsilat"],
  ["Vadesi geçen ödemeler", "Tahsilat & Karlılık", "Vade tarihi geçmiş açık tahsilatları filtreleyip takip edin.", "tahsilat"],
  ["Karlılık ekranı", "Tahsilat & Karlılık", "Gelir, gider, ödenen ve bekleyen tutar dengesini inceleyin.", "karlilik"],
  ["Tahsilat filtreleri", "Tahsilat & Karlılık", "Firma, durum, ödeme türü, ay ve yıl filtrelerini kontrollü uygulayın.", "tahsilat"],
  ["Görev oluşturma", "Görev Yönetimi", "Başlık, açıklama, öncelik, tarih ve sorumlu bilgisiyle görev açın.", "gorevler"],
  ["Görev atama", "Görev Yönetimi", "Görevi uygun ekip üyesine atayıp teslim tarihini belirleyin.", "gorevler"],
  ["Görev tamamlama ve tekrar açma", "Görev Yönetimi", "Tamamlanan görevi tarihçede koruyun veya yeniden açın.", "gorevler"],
  ["Otomatik satış görevleri", "Görev Yönetimi", "Teklif, takip ve onboarding aşamalarında üretilen görevleri yönetin.", "gorevler"],
  ["Müşteriye görünür görevler", "Görev Yönetimi", "Yalnız paylaşılması uygun görevleri müşteri paneline açın.", "gorevler"],
  ["Meta raporu oluşturma", "Raporlama Merkezi", "Meta kampanya metriklerinden dönemsel müşteri raporu hazırlayın.", "meta-analiz"],
  ["Google Ads raporu oluşturma", "Raporlama Merkezi", "Google Ads veya manuel performans verilerini raporlayın.", "google-analiz"],
  ["AI rapor yorumu", "Raporlama Merkezi", "Performans verilerinden Türkçe, ölçülü ve aksiyon odaklı yorum üretin.", "musteri-raporlari"],
  ["Executive rapor", "Raporlama Merkezi", "Teknik metrikleri müşteri dostu yönetici özetine dönüştürün.", "musteri-raporlari"],
  ["PDF Word Excel dışa aktarma", "Raporlama Merkezi", "Türkçe karakterleri koruyan rapor dosyalarını indirin.", "musteri-raporlari"],
  ["Meta Pixel kurulumu", "Meta Entegrasyonları", "Müşteri Pixel ID bilgisini kaydedip ölçümleme durumunu kontrol edin.", "entegrasyonlar"],
  ["Conversion API kurulumu", "Meta Entegrasyonları", "Sunucuda maskeli token ile CAPI test ve durum kontrolü yapın.", "entegrasyonlar"],
  ["Meta Test Event", "Meta Entegrasyonları", "Test Event Code ile gerçek müşteri verisi kullanmadan olay doğrulayın.", "entegrasyonlar"],
  ["Meta reklam hesabı bağlama", "Meta Entegrasyonları", "Business, Ads Account, Facebook Page ve Instagram hesaplarını firmaya eşleyin.", "reklam-hesabi-eslestirme"],
  ["Meta veri senkronizasyonu", "Meta Entegrasyonları", "Tarih aralığı seçip kampanya ve metrik verilerini güvenli biçimde çekin.", "meta-istihbarat"],
  ["Meta sorun giderme", "Meta Entegrasyonları", "Token, yetki, hesap ID ve veri dönemi sorunlarını teşhis edin.", "sistem-test-merkezi"],
  ["Google Ads müşteri hesabı", "Google Entegrasyonları", "Google Ads Customer ID ve MCC ilişkisini müşteriyle eşleyin.", "reklam-hesabi-eslestirme"],
  ["Google Analytics GA4", "Google Entegrasyonları", "Measurement ID ve property bilgisini analitik hazırlığı için kaydedin.", "entegrasyonlar"],
  ["Search Console hazırlığı", "Google Entegrasyonları", "Site sahipliği ve organik arama veri gereksinimlerini kontrol edin.", "entegrasyonlar"],
  ["Tag Manager ve dönüşüm takibi", "Google Entegrasyonları", "Etiket ve dönüşüm olaylarının isimlendirme planını yönetin.", "entegrasyonlar"],
  ["Website Analytics Entegrasyonları", "Google Entegrasyonları", "Meta Pixel, Dataset ID, GA4, Google servis hesabı, Search Console, Google Ads, GTM, Clarity ve Hotjar kurulum durumunu tek merkezde kontrol edin.", "website-analytics"],
  ["Meta Dataset ID ne işe yarar?", "Meta Entegrasyonları", "Dataset ID, Meta Pixel/Event Manager veri setini server-side olaylarla eşleştirmek ve Conversions API hazırlığı yapmak için kullanılır.", "website-analytics"],
  ["Google servis hesabı nedir?", "Google Entegrasyonları", "GA4 Data API ve Search Console raporlarını server-side çekmek için Google Cloud servis hesabı kullanılır; private key frontend'e gönderilmez.", "website-analytics"],
  ["GA4 Measurement ID ve Property ID farkı", "Google Entegrasyonları", "Measurement ID public site ölçümü içindir; Property ID server-side GA4 raporları için numeric mülk kimliğidir.", "website-analytics"],
  ["Search Console ve Google Ads readiness", "Google Entegrasyonları", "Search Console organik arama performansı; Google Ads API ise kampanya verisi için site URL, servis hesabı, developer token ve OAuth bilgileri ister.", "website-analytics"],
  ["GTM, Clarity ve Hotjar ne zaman kullanılır?", "Google Entegrasyonları", "GTM etiket yönetimi, Clarity ısı haritası/oturum kaydı, Hotjar davranış ve geri bildirim analizi için opsiyonel kaynaklardır.", "website-analytics"],
  ["Müşteri Kurulum Durumu ve Entegrasyon Sihirbazı", "CRM & Müşteriler", "Müşteri profilindeki Entegrasyonlar sekmesinde 14 adımlı kurulum ilerlemesini, Meta Dataset, GA4, Search Console, Google Ads, GTM, Clarity ve Hotjar bilgilerini yönetin.", "musteriler"],
  ["Müşteri keşfi", "HK Intelligence", "Şehir, ilçe ve sektör bazında işletme adayları bulun.", "musteri-kesfi"],
  ["Haritalar keşfi", "HK Intelligence", "Yerel işletme sinyallerini harita ve Google profili verileriyle inceleyin.", "haritalar"],
  ["Rakip analizi", "HK Intelligence", "Rakip görünürlüğü, reklam fırsatı ve önerilen aksiyonları karşılaştırın.", "rakip-analizi"],
  ["Lead workspace", "HK Intelligence", "Keşif sonuçlarını CRM ve teklif hazırlığına taşıyın.", "lead-analizi"],
  ["AI dijital denetim", "HK Intelligence", "Web, Instagram ve Google sinyallerinden denetim özeti üretin.", "ai-denetim"],
  ["AI Studio içerik üretimi", "AI Studio", "Marka, kanal ve hedefe göre kontrollü içerik taslağı üretin.", "ai-studio"],
  ["Prompt kullanımı", "AI Studio", "Tekrar kullanılabilir promptları bağlam ve çıktı beklentisiyle çalıştırın.", "prompt-uretimi"],
  ["AI sosyal medya planı", "AI Studio", "Sektör ve hedefe göre düzenlenebilir içerik takvimi hazırlayın.", "icerik-fikirleri"],
  ["Dosya yükleme", "Dosya & Belge Merkezi", "Dosya URL, tür, açıklama ve görünürlük bilgisiyle müşteri dosyası ekleyin.", "belgeler"],
  ["Dosya paylaşımı", "Dosya & Belge Merkezi", "Yalnız güvenli ve müşteri için uygun belgeleri görünür yapın.", "belgeler"],
  ["Kreatif Merkezi", "Dosya & Belge Merkezi", "Reklam görsellerini önizleme ve indirme için kreatif merkezine ekleyin.", "belgeler"],
  ["Kullanıcı rolleri", "Kullanıcı Yönetimi", "Admin, yönetici, editör ve müşteri rollerinin sınırlarını yönetin.", "kullanici-yonetimi"],
  ["Modül yetkileri", "Kullanıcı Yönetimi", "Ekip üyelerinin yalnız ihtiyaç duyduğu modüllere erişmesini sağlayın.", "kullanici-yonetimi"],
  ["Şifre ve hesap güvenliği", "Kullanıcı Yönetimi", "Geçici şifre, aktiflik ve güvenli hesap yönetimi uygulayın.", "kullanici-yonetimi"],
  ["SMTP ayarları", "Ayarlar", "Sistem e-postalarının sunucu bağlantısı ve gönderim durumunu yönetin.", "entegrasyonlar"],
  ["WhatsApp ayarları", "Ayarlar", "WhatsApp bağlantı kimliklerini ve hazır mesaj akışlarını yönetin.", "entegrasyonlar"],
  ["AI sağlayıcı ayarları", "Ayarlar", "Auto Router, OpenAI, Gemini, Groq, Claude, Manus, OpenRouter, Ollama ve Demo/Yerel Yedek Akış seçeneklerini güvenli biçimde yapılandırın.", "entegrasyonlar"],
  ["Merkezi AI Sağlayıcı Seçici nasıl çalışır?", "HK Agent Hub", "Google İstihbarat, Meta İstihbarat, AI Studio, Teklif Motoru ve Agent Hub aynı sağlayıcı listesini kullanır; yeni sağlayıcı tek merkezden tüm modüllere yansır.", "agent-hub"],
  ["Auto Router ne zaman kullanılır?", "HK Agent Hub", "Normal kullanımda Auto Router seçilmelidir. HK Intelligence görev tipini, aktif API anahtarlarını, hız/maliyet dengesini ve yedek akışı kontrol ederek sağlayıcı seçer.", "agent-hub"],
  ["Google İstihbarat neden Auto/Gemini önerir?", "HK Agent Hub", "Google İstihbarat arama görünürlüğü, SEO ve Google ekosistemi sinyalleri ürettiği için Auto Router ilk seçenek, Gemini ikinci seçenek, OpenAI üçüncü seçenek olarak değerlendirilir.", "agent-hub"],
  ["Manus ne zaman seçilmeli?", "HK Agent Hub", "Manus kısa reklam yorumları için varsayılan değildir; rakip analizi, pazar araştırması, fiyat karşılaştırması, sektör keşfi ve uzun web araştırması için seçilmelidir.", "agent-hub"],
  ["Groq ne zaman seçilmeli?", "HK Agent Hub", "Groq hızlı ve düşük maliyetli kısa cevaplarda uygundur; detaylı Google Ads analizi veya uzun raporlar için birincil tercih değildir.", "agent-hub"],
  ["Eksik API anahtarı nasıl anlaşılır?", "HK Agent Hub", "AI sağlayıcı kartlarında Aktif, Yapılandırılmadı, Eksik endpoint, Demo veya Yerel durumu görünür; gerçek secret değerleri tarayıcıya gönderilmez.", "agent-hub"],
  ["Agent Hub nedir?", "HK Agent Hub", "ChatGPT, Claude, Gemini, Groq, Manus ve yerel/alternatif modelleri görev tipine göre yöneten AI orkestrasyon merkezini kullanın.", "agent-hub"],
  ["Manus neden varsayılan değildir?", "HK Agent Hub", "Manus günlük kısa cevaplar yerine rakip analizi, pazar araştırması, fiyat karşılaştırması, sektör keşfi ve kapsamlı rapor görevlerinde kullanılır.", "agent-hub"],
  ["Hangi görevde hangi AI kullanılır?", "HK Agent Hub", "Reklam analizi, CRM özeti, içerik üretimi, derin araştırma ve hızlı cevap görevlerinin sağlayıcı önceliğini okuyun.", "agent-hub"],
  ["Agent Hub API key yönetimi", "HK Agent Hub", "Production’da API anahtarlarını Vercel Project Settings > Environment Variables alanına ekleyin; anahtarlar frontend’e gönderilmez.", "agent-hub"],
  ["Agent Hub yedek akış mantığı", "HK Agent Hub", "Bir sağlayıcı pasif, hatalı veya yapılandırılmamışsa sıradaki sağlayıcıya geçiş ve demo/yerel yedek akış davranışını kontrol edin.", "agent-hub"],
  ["İşlem kayıtları nasıl okunur?", "HK Agent Hub", "Görev tipi, seçilen sağlayıcı, durum, süre, tahmini maliyet, işlem metni ve hata alanlarıyla agent çalışmalarını denetleyin.", "agent-hub"],
  ["Agent maliyet takibi", "HK Agent Hub", "Bugünkü görev, aylık görev, tahmini maliyet, başarı oranı ve Manus derin araştırma sayısını takip edin.", "agent-hub"],
  ["Auto Router nasıl seçim yapar?", "HK Agent Hub", "Görev tipi, maliyet, sağlayıcı durumu, veri ihtiyacı ve yedek akışa göre OpenAI, Gemini, Claude, Groq, Manus veya demo sağlayıcıyı otomatik seçin.", "agent-hub"],
  ["AI seçim nedeni nasıl okunur?", "HK Agent Hub", "Run sonucundaki AI Seçim Nedeni kartında seçilen sağlayıcıyı, neden seçildiğini, kullanılmayan sağlayıcıları, eksik API anahtarlarını ve önerilen düzeltmeyi okuyun.", "agent-hub"],
  ["Manuel AI seçimi nasıl çalışır?", "HK Agent Hub", "Kullanıcı Groq, Gemini, OpenAI veya başka bir sağlayıcıyı elle seçerse sistem önce kesinlikle o sağlayıcıyı dener. Başarısız olursa yedek akışa geçer ve nedenini açıkça yazar.", "agent-hub"],
  ["Auto Router ne zaman devreye girer?", "HK Agent Hub", "Auto Router yalnız Otomatik Seçim seçildiğinde karar verir. Manuel seçimde router (yönlendirici) sadece öneri ve uyarı üretir, seçimi sessizce değiştirmez.", "agent-hub"],
  ["Groq seçilince neden başka sağlayıcı kullanılabilir?", "HK Agent Hub", "Groq manuel seçilmişse ilk deneme Groq ile yapılır. GROQ_API_KEY eksikse veya API hata verirse Demo/Yerel Yedek Akış kullanılır ve kartta seçilen sağlayıcı ile kullanılan sağlayıcı ayrı gösterilir.", "agent-hub"],
  ["Fallback/yedek akış nasıl okunur?", "HK Agent Hub", "Fallback (yedek akış), seçilen sağlayıcı çalışmadığında raporun bozulmaması için devreye giren güvenli alternatiftir. Kartlarda yedek akış nedeni, eksik environment değişkeni ve önerilen düzeltme görünür.", "agent-hub"],
  ["Sağlayıcı sağlık paneli nasıl yorumlanır?", "HK Agent Hub", "Sağlayıcı Sağlığı bölümünde health check (sağlık kontrolü), latency (yanıt süresi), hata sayısı, başarı oranı, tahmini maliyet ve Auto Router skoru izlenir.", "agent-hub"],
  ["Maliyet ve hata oranları ne anlama gelir?", "HK Agent Hub", "Maliyet tahmini token (işlem metni) ve sağlayıcı fiyat varsayımıyla hesaplanır. Hata oranı son 24 saatte başarısız veya yedek akışa düşen görevleri gösterir.", "agent-hub"],
  ["HK Intelligence Orchestrator nedir?", "HK Agent Hub", "HK Intelligence Orchestrator, sağlayıcı çıktısını son karar katmanı olarak düzenler; çelişkileri ayıklar, garanti vermeyen Türkçe rapor dili kullanır ve 7 günlük aksiyon planı üretir.", "agent-hub"],
  ["Çoklu AI işbirliği nasıl çalışır?", "HK Agent Hub", "Derin araştırma, pazar analizi, teklif üretimi ve müşteri raporlarında birden fazla sağlayıcının çıktısını HK Intelligence final raporunda birleştirin.", "agent-hub"],
  ["HK Intelligence final layer ne yapar?", "HK Agent Hub", "Sağlayıcı çıktısını doğrudan göstermeden yönetici özeti, bulgular, riskler, fırsatlar, aksiyonlar, 7 günlük plan ve müşteri mesajına dönüştürür.", "agent-hub"],
  ["Scheduled agent görevleri nasıl kurulur?", "HK Agent Hub", "Günlük, haftalık veya aylık agent görevleri oluşturup cron-ready endpoint ile güvenli şekilde çalıştırılacak hazırlığı yapın.", "agent-hub"],
  ["Agent Hub çıktı hazırlama ve e-posta taslakları", "HK Agent Hub", "Agent sonucundan Word, PDF, PowerPoint hazırlık verisi ve müşteriye gönderilebilir e-posta taslağı üretin.", "agent-hub"],
  ["Gerçek AI sağlayıcıları nasıl çalışır?", "HK Agent Hub", "OpenAI, Gemini, Groq, Claude, OpenRouter, Ollama ve Manus API anahtarı varsa server-side gerçek çağrı yapar; yoksa güvenli demo/yedek akış üretir.", "agent-hub"],
  ["Agent Memory nedir?", "HK Agent Hub", "Müşteri bazlı geçmiş agent sonuçları, öneriler ve uygulanmış aksiyonları saklayarak sonraki analizlere bağlam sağlar.", "agent-hub"],
  ["Maliyet paneli nasıl okunur?", "HK Agent Hub", "Bugünkü ve aylık tahmini maliyeti, sağlayıcı bazlı maliyeti, ortalama görev maliyetini ve yedek akış oranını kontrol edin.", "agent-hub"],
  ["Queue ne işe yarar?", "HK Agent Hub", "Uzun süren agent görevlerini sırada, çalışıyor, başarısız veya iptal edildi durumlarıyla izleyin; gerekirse tekrar çalıştırın veya iptal edin.", "agent-hub"],
  ["Export dosyaları nasıl üretilir?", "HK Agent Hub", "PDF için print-ready HTML, Word için metin/markdown, PowerPoint için slayt taslağı hazırlanır; bozuk indirme linki gösterilmez.", "agent-hub"],
  ["E-posta ve WhatsApp raporları nasıl kullanılır?", "HK Agent Hub", "Final rapordan müşteri e-posta taslağı, onaylı gönderim ve WhatsApp’a uygun kısa özet üretin; müşteri e-postası yoksa sistem uyarır.", "agent-hub"],
  ["Entegrasyon Kontrolü nasıl kullanılır?", "HK Agent Hub", "OpenAI, Gemini, Groq, Claude, OpenRouter, Manus, Ollama, Resend, Discord, Meta, Google Ads, Supabase ve Cron Secret durumlarını secret göstermeden kontrol edin.", "agent-hub"],
  ["Slack neden kaldırıldı?", "HK Agent Hub", "Agent Hub içinde Slack bildirimi kullanıcı arayüzünden kaldırıldı; bildirim için sade ve tek akış olarak Discord Webhook desteklenir.", "agent-hub"],
  ["Discord nasıl bağlanır?", "HK Agent Hub", "Discord bildirimi için DISCORD_WEBHOOK_URL değerini Vercel Environment Variables alanına ekleyin; yoksa Discord butonu gizlenir.", "agent-hub"],
  ["Sonuç nasıl kaydedilir?", "HK Agent Hub", "Sonucu Kaydet butonu agent_runs kaydını saved_at, saved_by ve saved_title alanlarıyla işaretler ve Agent Kayıtları içinde saklar.", "agent-hub"],
  ["AI Hafızasına kaydetme ne işe yarar?", "HK Agent Hub", "AI Hafızasına Kaydet butonu analiz özetini, aksiyonları ve riskleri agent_memories tablosuna müşteri bağlamı olarak kaydeder.", "agent-hub"],
  ["Training Center nasıl kullanılır?", "HK Agent Hub", "HK Intelligence’ın garanti vermeyen dil, sade müşteri açıklaması, risk anlatımı ve 7 günlük plan kurallarını yönetin.", "agent-hub"],
  ["Prompt Versioning nedir?", "HK Agent Hub", "Prompt sürümlerini saklayın, değişiklik notu ekleyin ve gerektiğinde eski sürüme geri dönün.", "agent-hub"],
  ["Benchmark nasıl yapılır?", "HK Agent Hub", "Aynı promptu birden fazla AI sağlayıcısına verip süre, maliyet, güven skoru ve HK Intelligence kararını karşılaştırın.", "agent-hub"],
  ["Meta/Google veri kaynakları Agent Hub’a nasıl bağlanır?", "HK Agent Hub", "Müşteri seçildiğinde mevcut Meta, Google, reklam raporu ve manuel kayıtlar prompt bağlamına veri kaynağı olarak eklenebilir; veri yoksa açıkça eksik veri yazılır.", "agent-hub"],
  ["Agent Hub Vercel env listesi", "HK Agent Hub", "Production’da OPENAI_API_KEY, GEMINI_API_KEY, GROQ_API_KEY, ANTHROPIC_API_KEY, OPENROUTER_API_KEY, MANUS_API_KEY, MANUS_API_BASE_URL, MANUS_API_ENDPOINT, OLLAMA_BASE_URL, AGENT_HUB_CRON_SECRET, SMTP/RESEND ve DISCORD_WEBHOOK_URL değerlerini Vercel Environment Variables alanına ekleyin.", "agent-hub"],
  ["Müşterilere direkt erişim", "CRM & Müşteriler", "Admin panelde Müşteriler öğesini Müşteri & Satış grubunun ilk sırasında ve dashboard hızlı aksiyonlarında bulun.", "musteriler"],
  ["Admin buton okunabilirliği standardı", "Ayarlar", "Siyah/dark primary butonlar yerine açık temada okunur cyan, amber, blue veya border tabanlı admin buton stillerini kullanın.", "sistem-rehberi"],
  ["Tam sistem yedeği nasıl alınır?", "Ayarlar", "Veri Aktarma ekranında yalnız admin rolüyle Tam Yedek İndir butonunu kullanarak güvenli JSON, CSV, Excel uyumlu CSV veya özet rapor çıktısı alın.", "veri-aktarma"],
  ["Yedeğe hangi veriler dahil edilir?", "Ayarlar", "Müşteri, kampanya, görev, tahsilat, belge, rapor ve operasyon özetleri yedeğe dahil edilir; tablo bulunamazsa özet raporda uyarı gösterilir.", "veri-aktarma"],
  ["Hangi veriler dışarı aktarılmaz?", "Ayarlar", "API key, access token, refresh token, secret, password, hash, service role ve agent provider secret değerleri güvenlik nedeniyle export dışı bırakılır.", "veri-aktarma"],
  ["Dosyadan geri yükleme nasıl yapılır?", "Ayarlar", "Veri Aktarma ekranında dosya seçin, import tipini ve çakışma davranışını belirleyin, önce Önizleme yapın ve yalnız onaydan sonra içe aktarın.", "veri-aktarma"],
  ["Müşteri bilgileri nasıl Excel/PDF/Word alınır?", "CRM & Müşteriler", "Müşteriler ekranında aktif, pasif, arşivli veya silinen görünümünü filtreleyip Müşteri Bilgilerini İndir grubundan Excel, Word, PDF veya CSV seçin.", "musteriler"],
  ["Rapor çıktıları nasıl hazırlanır?", "Raporlama Merkezi", "Rapor çıktıları ekran görüntüsü yerine HK Dijital başlıklı profesyonel rapor şablonu, yönetici özeti, tablo, bulgular, riskler, fırsatlar ve aksiyon planı ile oluşturulur.", "raporlar"],
  ["Import önizleme neden zorunludur?", "Ayarlar", "Önizleme kayıt sayısı, bozuk kayıt, çakışma ve uyarıları gösterir; destructive olmayan güvenli import için onay öncesi kontrol zorunludur.", "veri-aktarma"],
  ["Sistem ayarları", "Ayarlar", "Performans, güvenlik, yedekleme ve uygulama tercihlerini yönetin.", "sistem-ayarlari"],
  ["Butonlar ve İşlem Mantığı", "Ayarlar", "Kaydetme, güncelleme, arşivleme, hata bildirimi ve kalıcılık davranışlarını doğrulayın.", "sistem-test-merkezi"],
  ["Logo ve marka yönetimi", "Web Site Yönetimi", "Public site logo, favicon ve marka metinlerini güncelleyin.", "web-sitesi-yonetimi"],
  ["Hizmet ve paket yönetimi", "Web Site Yönetimi", "Public sitedeki hizmet ve paket içeriklerini düzenleyin.", "web-sitesi-yonetimi"],
  ["İletişim ve sosyal bağlantılar", "Web Site Yönetimi", "Telefon, e-posta, adres ve sosyal medya bağlantılarını yönetin.", "web-sitesi-yonetimi"],
  ["Müşteri panelinde raporlar", "Müşteri Paneli", "Yayınlanmış ve görünür raporları müşteri gözüyle kontrol edin.", "musteriler"],
  ["Müşteri panelinde ödeme ve görevler", "Müşteri Paneli", "Yalnız görünür ödeme ve görev kayıtlarının doğru yansıdığını doğrulayın.", "musteriler"],
  ["Müşteri panelinde dosyalar", "Müşteri Paneli", "Paylaşılan belge ve kreatiflerin açılma ve indirme akışını kontrol edin.", "musteriler"],
  ["Pixel çalışmıyor", "Sorun Giderme", "Pixel ID, public sayfa kapsamı ve Events Manager test durumunu kontrol edin.", "sistem-test-merkezi"],
  ["Meta verisi gelmiyor", "Sorun Giderme", "Token, reklam hesabı, tarih aralığı ve yetki hatalarını sırasıyla inceleyin.", "sistem-test-merkezi"],
  ["Google Ads bağlanmıyor", "Sorun Giderme", "Customer ID, MCC, OAuth ve API yapılandırmasını doğrulayın.", "sistem-test-merkezi"],
  ["Müşteri giriş yapamıyor", "Sorun Giderme", "Kullanıcının aktifliği, firma bağı ve rolünü kontrol edin.", "kullanici-yonetimi"],
  ["Rapor veya export görünmüyor", "Sorun Giderme", "Rapor durumu, müşteri görünürlüğü ve dosya üretim sonucunu kontrol edin.", "musteri-raporlari"],
  ["Görev veya ödeme görünmüyor", "Sorun Giderme", "Arşiv, tarih, müşteri ve görünürlük filtrelerini kontrol edin.", "sistem-test-merkezi"],
  ["AI çalışmıyor", "Sorun Giderme", "Aktif sağlayıcı, model, API anahtarı ve demo yedek akış durumunu kontrol edin.", "sistem-test-merkezi"],
  ["Admin modülleri ve bakım yapısı", "Ayarlar", "AdminDashboard içindeki büyük modüllerin küçük bileşenlere nasıl ayrıldığını ve QA performans uyarılarının nasıl yorumlanacağını öğrenin.", "sistem-rehberi"],
  ["QA Center nasıl kullanılır?", "Ayarlar", "Sayfa, API, migration, env, güvenlik ve buton risklerini tek QA ekranından tarayın.", "qa-center"],
  ["HK Reklam Doktoru Pro nasıl yorumlanır?", "Raporlama Merkezi", "Reklam sağlık skoru, doktor teşhisleri, reçete aksiyonları, kreatif yorgunluğu ve müşteri özetini birlikte okuyun.", "ad-insights"],
  ["Görev şablonları nasıl kullanılır?", "Görev Yönetimi", "Onboarding, Pixel, rapor, teklif takip ve tahsilat hatırlatma görevlerini hazır şablondan oluşturun.", "musteriler"],
  ["Tekrarlayan görev nasıl oluşturulur?", "Görev Yönetimi", "Günlük, haftalık, aylık veya özel tekrar kuralı ile düzenli operasyon görevleri planlayın.", "musteriler"],
  ["Alt görev nedir?", "Görev Yönetimi", "Büyük işleri küçük kontrol maddelerine bölerek ana görevin altında takip edin.", "musteriler"],
  ["Reklam sağlık skoru ne anlama gelir?", "Raporlama Merkezi", "CTR, CPC, CPM, lead/mesaj sinyali, frekans ve bütçe verimliliğinden oluşan 0-100 performans puanını yorumlayın.", "ad-insights"],
  ["Boşa harcanan bütçe nasıl yorumlanır?", "Raporlama Merkezi", "Düşük CTR veya yüksek CPC sinyali veren reklam harcamasını durdurma, izleme veya kreatif yenileme kararı için kullanın.", "ad-insights"],
  ["Yeni menü kategorizasyonu", "Ayarlar", "Kontrol Merkezi, Müşteri & Satış, Ajans Operasyonu, Reklam & Raporlama, İçerik & AI, Entegrasyonlar, Araçlar & Yardım ve Ayarlar kategorilerini doğru okuyun.", "sistem-rehberi"],
  ["Müşteri & Satış akışı", "Müşteri & Satış", "Müşteri keşfinden CRM, fırsat pipeline, teklif, takip ve kazanıldı/kaybedildi analizine kadar satış yolunu yönetin.", "musteri-kesfi"],
  ["Ajans Operasyonu akışı", "Ajans Operasyonu", "Görevler, takvim, tahsilat, onboarding ve ajans hedeflerini günlük operasyon planına bağlayın.", "gorevler"],
  ["Teklif Takip Merkezi", "Müşteri & Satış", "Teklif gönderimi sonrası 3, 7, 14 ve 21 günlük takip akışlarını izleyin ve hızlı mesajları kopyalayın.", "teklif-takip-merkezi"],
  ["Takip kuralları", "Müşteri & Satış", "Tekliften 3 gün sonra ilk takip, 7 gün sonra ikinci takip, 14 gün sonra son takip ve 21 gün sonra pasif değerlendirme kuralını uygulayın.", "teklif-takip-merkezi"],
  ["Kazanıldı / Kaybedildi Analizi", "Müşteri & Satış", "Kapanan fırsatlardan sektör, şehir, paket, bütçe ve itiraz öğrenimi çıkarın.", "kazanildi-kaybedildi-analizi"],
  ["AI Satış Koçu", "İçerik & AI", "Lead veya fırsat için arama metni, WhatsApp mesajı, e-posta taslağı, itiraz cevabı ve kapanış cümlesi üretin.", "ai-satis-kocu"],
  ["Müşteri segmentleri", "Müşteri & Satış", "Sıcak lead, teklif bekliyor, takipte, pasif, kazanıldı, kaybedildi ve tahsilat riski segmentlerini yorumlayın.", "lead-workspace"],
  ["Tahsilat + onboarding görevleri", "Ajans Operasyonu", "Kazanılan fırsat sonrası ilk ödeme, sözleşme, reklam erişimleri, Pixel, Analytics, içerik ve ilk rapor görevlerini oluşturun.", "gorevler"],
  ["Ajans Hedef Panosu", "Ajans Operasyonu", "Aylık gelir, müşteri, teklif, görüşme ve tahsilat hedeflerini takip edip hedefe kalan aksiyonu belirleyin.", "ajans-hedefleri"],
  ["Gerçek / Tahmini / Eksik veri etiketleri", "Dashboard & Kontrol Merkezi", "Karar panellerinde verinin gerçek kayıttan mı, tahminden mi yoksa eksik bilgiden mi geldiğini kontrol edin.", "qa-center"],
  ["Mobil Operasyon Modu gelişmiş kullanım", "Ayarlar", "Saha kullanımında büyük buton, tek sütun kart ve kolay basılabilir aksiyon düzenini açıp kapatın.", "mobil-operasyon-modu"],
  ["Migration sonrası Supabase kontrolü", "Ayarlar", "Yeni migration çalıştırıldıktan sonra PostgREST schema cache yenileme ve QA Merkezi kontrollerini doğrulayın.", "qa-center"]
];

const customerJourneyGuide: SystemGuideSeed = {
  slug: "bir-musterinin-seruveni",
  title: "Bir Müşterinin Serüveni",
  category: "Müşteri Serüveni",
  description: "İlk kayıttan sözleşme bitimine kadar HK Dijital’de müşteri yönetimi nasıl yapılır?",
  route: "/hk-admin/musteriler",
  content: {
    purpose: "Bu rehber, yeni bir müşteriyle ilk temas kurulduğu andan kampanya kurulumu, reklam verileri, raporlama, tahsilat, görev takibi, yedekleme ve sözleşme bitişine kadar tüm süreci adım adım anlatır.",
    whenToUse: "Yeni ekip arkadaşı onboarding sürecinde, yeni müşteri açarken, müşteri bilgilerini tamamlarken, rapor/tahsilat/görev akışını kontrol ederken ve sözleşme kapanışında kullanılır.",
    steps: [
      "Lead → Firma Kaydı → Müşteri Hesabı → Entegrasyonlar → Kampanya → Rapor → Tahsilat → Revizyon → Yenileme / Kapanış akışını takip edin.",
      "1. Aday müşteri / lead oluşturma: Müşteri & Satış > Müşteri Keşfi veya CRM ekranına gidin. CRM’e Kaydet, Lead Oluştur veya Müşteri Keşfine Git aksiyonuyla aday kaydı açın. Sonraki adım: ilk iletişim bilgisini tamamlayın.",
      "2. İlk iletişim bilgilerini kaydetme: CRM veya Lead Workspace içinde yetkili adı, telefon, e-posta, Instagram, website ve not alanlarını doldurun. Gizli token veya şifreleri not alanına yazmayın.",
      "3. Firma ve müşteri kaydı oluşturma: Müşteri & Satış > Müşteriler ekranında + Yeni Firma Oluştur butonunu kullanın. Firma adı, sektör, şehir, telefon, e-posta ve not bilgisini girin.",
      "4. Müşteri giriş hesabı oluşturma: Müşteriler ekranında + Müşteri Giriş Hesabı Oluştur butonunu kullanın. Geçici şifre ve firma eşleşmesini kontrol edin.",
      "5. Yetkili kişi, telefon, e-posta, sektör ve şehir bilgilerini tamamlama: Müşteri detayını aç, Düzenle ve Kaydet butonlarıyla eksik alanları tamamlayın.",
      "6. Sosyal medya, web sitesi ve reklam hesap bilgilerini ekleme: Müşteri profili ve entegrasyon alanlarında website, Instagram, Facebook, Meta Business ve Google bilgilerini girin.",
      "7. Meta Business / Pixel / reklam hesabı bilgilerini kaydetme: Entegrasyonlar > Meta Entegrasyonları veya müşteri profilindeki reklam hesap alanında Meta bilgisi ekle, Token test et ve Verileri senkronize et akışını kullanın.",
      "8. Google Ads / Analytics / Search Console / Maps bilgilerini kaydetme: Google Entegrasyonları veya Google İstihbarat alanında Google Ads ID, Analytics ID, Search Console ve Maps bilgilerini ekleyin; Test Et butonuyla doğrulayın.",
      "9. Token, API ve entegrasyon bilgilerini güvenli ekleme: Ayarlar > Entegrasyonlar veya Agent Hub > Entegrasyon Kontrolü ekranını kullanın. API anahtarı ekle ve Test Et aksiyonlarını kullanın; tokenları not alanlarına yazmayın.",
      "9.a. Müşteri Kurulum Durumu ve Entegrasyon Sihirbazı: Müşteri profili > Entegrasyonlar sekmesinde 14 adımı izleyin. Firma, müşteri hesabı, domain, Meta Business, Pixel, Dataset, GA4, Search Console, Google Ads, Tag Manager, Clarity, Hotjar, ilk kampanya ve ilk rapor adımları ilerleme çubuğunda görünür.",
      "9.b. Entegrasyon alanlarını müşteri profilinden düzenleme: Meta Dataset ID, GA4 Property ID, Search Console URL, Google Ads Customer ID, GTM ID, Clarity ve Hotjar değerlerini Entegrasyonlar sekmesine girin. Secret/private key gibi bilgiler burada açık saklanmaz.",
      "9.c. Website Analytics Center özeti: /hk-admin/website-analytics ekranında tüm müşterilerin entegrasyon yüzdesini ve genel env durumunu kontrol edin; müşteri bazlı düzenleme için Müşteri Profilinde Düzenle butonunu kullanın.",
      "10. Kampanya oluşturma: Reklam & Raporlama > Kampanyalar alanında Kampanya oluştur, Rapor ekle veya Veri gir butonlarını kullanın. Reklam bütçesi ve hizmet bedelini ayrı takip edin.",
      "11. Reklam bütçesi ve hizmet bedeli belirleme: Kampanya, teklif veya tahsilat ekranında reklam bütçesini medya harcaması; hizmet bedelini ajans geliri olarak ayrı kaydedin.",
      "12. Görev ve yapılacaklar oluşturma: Ajans Operasyonu > Görevler veya müşteri profilindeki Yapılacaklar sekmesinde Görev oluştur ve Takip görevi oluştur aksiyonlarını kullanın.",
      "13. İçerik / kreatif / belge dosyalarını ekleme: Ajans Operasyonu > Belgeler alanında Belge ekle ve Müşteriye görünür yap seçeneklerini kontrollü kullanın.",
      "14. Rapor verisi girme veya entegrasyonla çekme: Reklam & Raporlama > Aylık Raporlar ekranında Rapor oluştur, veri gir veya entegrasyondan çek akışını kullanın.",
      "15. AI ile reklam yorumu / HK Intelligence analizi alma: Reklam Doktoru Pro veya Agent Hub’da Yeni Agent Görevi, Auto Router, Sonucu Kaydet ve AI Hafızasına Kaydet aksiyonlarını kullanın.",
      "16. Müşteriye görünür alanları kontrol etme: Müşteri profili görünürlük ayarlarında rapor, belge, görev ve notların müşteriye uygun olup olmadığını kontrol edin.",
      "17. Müşteri paneli erişimini test etme: Müşteri hesabıyla panel görünürlüğünü kontrol edin; görünmemesi gereken iç not, token veya dahili görev paylaşılmamalıdır.",
      "18. Tahsilat ve ödeme takibi: Ajans Operasyonu > Tahsilat ekranında Tahsilat ekle, Ödeme durumu güncelle ve Filtrele aksiyonlarını kullanın.",
      "19. Aylık rapor oluşturma: Reklam & Raporlama > Aylık Raporlar alanında Rapor oluştur, AI yorumla ve PDF/Word/Excel indir aksiyonlarını kullanın.",
      "20. Revizyon / iyileştirme planı oluşturma: Rapor, görev ve Agent Hub çıktılarından 7 günlük aksiyon planı oluşturun; satış veya ciro garantisi vermeyin.",
      "21. Sözleşme yenileme, pasife alma veya arşivleme: Müşteriler > Müşteri detayı alanında Pasifleştir, Arşivle veya Kapanış notu ekle akışını kullanın.",
      "22. Sözleşme bitiminde veri yedekleme ve kapanış notu: Veri Aktarma ekranında Tam Yedek İndir, gerekirse Önizleme ve Onayla ve İçe Aktar akışını kullanın; son rapor ve ödeme durumunu kontrol edin."
    ],
    example: "Yeni bir müşteri için önce Müşteriler ekranında firma kaydı açın, müşteri giriş hesabını oluşturun, Meta/Google bilgilerini ekleyin, ilk kampanya ve görevleri planlayın, tahsilat kaydını açın, ilk ay raporunu oluşturun ve müşteri panelinde görünürlük kontrolü yapın.",
    commonErrors: [
      "Token, API anahtarı veya şifreyi müşteri notu gibi açık alanlara yazmak.",
      "Reklam bütçesi ile ajans hizmet bedelini aynı kayıt gibi takip etmek.",
      "Müşteriye görünür yapılacak rapor, belge veya notları kontrol etmeden paylaşmak.",
      "Sözleşme bitiminde son rapor, ödeme durumu ve veri yedeğini kontrol etmeden müşteriyi pasife almak."
    ],
    tips: [
      "Hızlı aksiyonlar: Müşterilere Git, Yeni Firma Oluştur, Müşteri Keşfine Git, Kampanya Oluştur, Tahsilat Ekle, Rapor Oluştur, Agent Hub’a Git, Veri Yedekleme.",
      "Yeni müşteri checklist: firma adı, yetkili, telefon, e-posta, şehir/sektör, website/Instagram, müşteri hesabı, panel erişimi, Meta Pixel, Google Ads ID, Analytics ID, bütçe, hizmet bedeli, ilk kampanya, görevler, rapor görünürlüğü, tahsilat ve ilk ay raporu.",
      "Raporlarda ölçülü ve veriye dayalı dil kullanın; satış, lead veya ciro garantisi vermeyin.",
      "Kapanışta müşteri pasife alınmadan önce yedek ve kapanış notu oluşturun."
    ],
    warnings: [
      "Güvenlik: Token, API anahtarı ve şifre gibi bilgiler yalnızca güvenli entegrasyon alanlarına girilmelidir.",
      "Müşteri paneli: Müşteriye görünür rapor, belge ve notlar gönderilmeden önce mutlaka kontrol edilmelidir.",
      "Tahsilat: Reklam bütçesi ve hizmet bedeli ayrı takip edilmelidir.",
      "Kapanış: Sözleşme bitiminde son rapor, ödeme durumu ve veri yedeği kontrol edilmelidir."
    ]
  }
};

function slugify(value: string) {
  return value.toLocaleLowerCase("tr").normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/ı/g, "i").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

export const systemGuideSeeds: SystemGuideSeed[] = [customerJourneyGuide, ...definitions.map(([title, category, description, route]) => ({
  slug: slugify(title),
  title,
  category,
  description,
  route: route ? `/hk-admin/${route}` : "/hk-admin",
  content: {
    purpose: description,
    whenToUse: `${title} işlemini uygulamanız veya ilgili kaydın doğru çalıştığını doğrulamanız gerektiğinde kullanılır.`,
    steps: [
      `${route ? `/hk-admin/${route}` : "/hk-admin"} ekranını yetkili hesabınızla açın.`,
      `${description} İlgili müşteri veya kaydı seçip mevcut bilgileri kontrol edin.`,
      "Değişiklikleri kaydetmeden önce görünürlük, tarih ve durum alanlarını doğrulayın; işlem sonucunu üst bildirimden kontrol edin."
    ],
    example: `${title} sırasında örnek bir kayıt üzerinde işlem yapın; kaydetme sonrasında listeyi yenileyerek sonucun kalıcı olduğunu doğrulayın.`,
    commonErrors: ["Yanlış müşteri veya tarih filtresiyle işlem yapmak.", "Kaydetmeden ekrandan ayrılmak ya da görünürlük alanını kontrol etmemek."],
    tips: ["Önce filtreleri temizleyip doğru kaydı seçin.", "Kritik değişikliklerden sonra ilgili müşteri panelini veya raporu kontrol edin."],
    warnings: ["Token, API anahtarı, dahili not veya müşteri için gizli bilgileri paylaşılabilir alanlara yazmayın.", "Silme yerine mevcutsa arşivleme akışını tercih edin."]
  }
}))];
