import { NextResponse } from "next/server";
import { requireModuleAccess } from "@/lib/permissions";
import { getSafeSupabaseError, hasSupabaseConfig, supabaseRest } from "@/lib/supabase";

function text(value: unknown, max = 500) {
  return String(value || "").replace(/\s+/g, " ").trim().slice(0, max);
}

function textArray(value: unknown, maxItems = 20, maxLength = 120) {
  return Array.isArray(value)
    ? value.map((item) => text(item, maxLength)).filter(Boolean).slice(0, maxItems)
    : text(value, maxLength).split(",").map((item) => item.trim()).filter(Boolean).slice(0, maxItems);
}

function bool(value: unknown, fallback = false) {
  return typeof value === "boolean" ? value : fallback;
}

function normalizePlan(body: Record<string, unknown>, userId?: string | null) {
  const name = text(body.name, 160);
  if (name.length < 3) throw new Error("Plan adı zorunludur.");
  const autoPublish = bool(body.auto_publish ?? body.autoPublish, false);
  return {
    name,
    status: ["draft", "active", "paused", "completed", "archived"].includes(text(body.status, 40)) ? text(body.status, 40) : "draft",
    service: text(body.service, 160),
    region: text(body.region, 100),
    audience: text(body.audience, 220),
    objective: text(body.objective, 240),
    weekly_count: Math.max(1, Math.min(14, Number(body.weekly_count ?? body.weeklyCount ?? 2) || 2)),
    start_date: text(body.start_date ?? body.startDate, 40) || null,
    end_date: text(body.end_date ?? body.endDate, 40) || null,
    preferred_days: textArray(body.preferred_days ?? body.preferredDays, 7, 20),
    preferred_time: text(body.preferred_time ?? body.preferredTime, 20) || "10:00",
    content_types: textArray(body.content_types ?? body.contentTypes, 10, 80),
    primary_keywords: textArray(body.primary_keywords ?? body.primaryKeywords, 20, 120),
    excluded_keywords: textArray(body.excluded_keywords ?? body.excludedKeywords, 20, 120),
    tone: text(body.tone, 80) || "Profesyonel",
    average_length: text(body.average_length ?? body.averageLength, 80) || "Standart: 1000–1400 kelime",
    auto_generate_drafts: bool(body.auto_generate_drafts ?? body.autoGenerateDrafts, true),
    auto_publish: autoPublish,
    require_approval: autoPublish ? true : bool(body.require_approval ?? body.requireApproval, true),
    created_by: userId || null
  };
}

function normalizeItem(planId: string, item: Record<string, unknown>) {
  const title = text(item.title, 180);
  const slug = text(item.slug, 120);
  if (!title || !slug) throw new Error("Plan öğelerinde başlık ve slug zorunludur.");
  return {
    plan_id: planId,
    blog_post_id: text(item.blog_post_id ?? item.blogPostId, 80) || null,
    title,
    slug,
    primary_keyword: text(item.primary_keyword ?? item.primaryKeyword, 140),
    secondary_keywords: textArray(item.secondary_keywords ?? item.secondaryKeywords, 8, 100),
    search_intent: text(item.search_intent ?? item.searchIntent, 120),
    target_audience: text(item.target_audience ?? item.targetAudience, 180),
    content_type: text(item.content_type ?? item.contentType, 100),
    scheduled_at: text(item.scheduled_at ?? item.scheduledAt, 80) || null,
    status: ["planned", "draft_ready", "draft_created", "scheduled", "published", "skipped"].includes(text(item.status, 40)) ? text(item.status, 40) : "planned",
    priority: text(item.priority, 40) || "Orta",
    rationale: text(item.rationale, 700),
    source_signals: textArray(item.source_signals ?? item.sourceSignals, 8, 80),
    last_error: text(item.last_error ?? item.lastError, 400) || null
  };
}

export async function GET() {
  const session = await requireModuleAccess("blog-seo");
  if (!session) return NextResponse.json({ error: "Yetkisiz erişim" }, { status: 403 });
  if (!hasSupabaseConfig()) return NextResponse.json({ plans: [], source: "empty", message: "Supabase yapılandırılmadı; içerik planı kaydı kullanılamaz." });
  try {
    const plans = await supabaseRest<Record<string, unknown>[]>("content_plans?select=*,content_plan_items(*)&order=updated_at.desc&limit=50");
    return NextResponse.json({ plans, source: "database" });
  } catch (error) {
    return NextResponse.json({ error: getSafeSupabaseError(error).detail }, { status: 500 });
  }
}

export async function POST(request: Request) {
  const session = await requireModuleAccess("blog-seo");
  if (!session) return NextResponse.json({ error: "Yetkisiz erişim" }, { status: 403 });
  if (!hasSupabaseConfig()) return NextResponse.json({ error: "Supabase yapılandırması yok. Canlı içerik planı kaydı için migration ve veritabanı gerekir." }, { status: 500 });
  try {
    const body = await request.json().catch(() => ({})) as Record<string, unknown>;
    const planRows = await supabaseRest<Record<string, unknown>[]>("content_plans", {
      method: "POST",
      body: JSON.stringify(normalizePlan(body, session.profileId))
    });
    const plan = planRows[0];
    const planId = String(plan?.id || "");
    const rawItems = Array.isArray(body.items) ? body.items : [];
    const itemsPayload = rawItems.slice(0, 40).map((item) => normalizeItem(planId, item as Record<string, unknown>));
    const items = itemsPayload.length
      ? await supabaseRest<Record<string, unknown>[]>("content_plan_items", { method: "POST", body: JSON.stringify(itemsPayload) })
      : [];
    return NextResponse.json({ plan: { ...plan, content_plan_items: items } });
  } catch (error) {
    return NextResponse.json({ error: getSafeSupabaseError(error).detail }, { status: 400 });
  }
}
